apiVersion: apps/v1
kind: Deployment
metadata:
  name: bicap-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bicap-redis
  template:
    metadata:
      labels:
        app: bicap-redis
    spec:
      containers:
        - name: redis
          image: redis:7.4-alpine
          ports:
            - containerPort: 6379
