import { useEffect, useMemo, useState } from 'react'
import '../shipping-workspace.css'
import '../transaction-hardening.css'
import { createDriver, createVehicle, getDrivers, getUsers, getVehicles, updateDriver, updateVehicle } from '../services/businessService'
import { createShipment, getEligibleShipmentOrders, getMyNotifications, getShipmentReportsForReview, getShipments, markNotificationRead, updateShipmentStatus } from '../services/workflowService.js'
import { getErrorMessage } from '../utils/helpers'

const initialDriverForm = { driverCode: '', licenseNo: '', userId: '', status: 'ACTIVE' }
const initialVehicleForm = { plateNo: '', vehicleType: '', capacity: '', status: 'ACTIVE' }
const initialShipmentForm = { orderId: '', driverId: '', vehicleId: '', note: '' }
const initialShipmentStatusForm = { status: 'ASSIGNED', note: '' }
const shipmentStatuses = ['ASSIGNED', 'PICKED_UP', 'IN_TRANSIT', 'DELIVERED', 'REJECTED', 'DISPUTED', 'ESCALATED', 'CANCELLED']

function Icon({ children, fill = false }) { return <span className={`material-symbols-outlined${fill ? ' fill' : ''}`}>{children}</span> }
function safeList(list) { return Array.isArray(list) ? list : [] }
function toPositiveNumber(value) { const numeric = Number(value); return Number.isFinite(numeric) && numeric > 0 ? numeric : null }
function formatCapacity(value) { const numeric = Number(value); return Number.isFinite(numeric) ? `${numeric.toLocaleString('vi-VN')} kg` : 'N/A' }
function Status({ value }) { const key = String(value || 'ASSIGNED').toLowerCase(); return <span className={`ship-status ${key}`}>{value || 'ASSIGNED'}</span> }

export function ShippingWorkspacePage({ module = 'overview' }) {
  const [drivers, setDrivers] = useState([])
  const [vehicles, setVehicles] = useState([])
  const [eligibleOrders, setEligibleOrders] = useState([])
  const [shipments, setShipments] = useState([])
  const [shipmentReports, setShipmentReports] = useState([])
  const [notifications, setNotifications] = useState([])
  const [users, setUsers] = useState([])
  const [driverForm, setDriverForm] = useState(initialDriverForm)
  const [vehicleForm, setVehicleForm] = useState(initialVehicleForm)
  const [shipmentForm, setShipmentForm] = useState(initialShipmentForm)
  const [shipmentStatusForm, setShipmentStatusForm] = useState(initialShipmentStatusForm)
  const [selectedDriverId, setSelectedDriverId] = useState('')
  const [selectedVehicleId, setSelectedVehicleId] = useState('')
  const [selectedShipmentId, setSelectedShipmentId] = useState('')
  const [loading, setLoading] = useState(true)
  const [savingShipment, setSavingShipment] = useState(false)
  const [savingDriver, setSavingDriver] = useState(false)
  const [savingVehicle, setSavingVehicle] = useState(false)
  const [error, setError] = useState('')
  const [success, setSuccess] = useState('')

  const displayShipments = safeList(shipments)
  const displayDrivers = safeList(drivers)
  const displayVehicles = safeList(vehicles)
  const selectedShipment = useMemo(() => displayShipments.find((item) => String(item.shipmentId) === String(selectedShipmentId)) || displayShipments[0] || null, [displayShipments, selectedShipmentId])
  const activeDrivers = useMemo(() => displayDrivers.filter((item) => item.status === 'ACTIVE'), [displayDrivers])
  const activeVehicles = useMemo(() => displayVehicles.filter((item) => item.status === 'ACTIVE'), [displayVehicles])
  const availableUsers = useMemo(() => users.filter((item) => item.status === 'ACTIVE'), [users])

  useEffect(() => { loadWorkspace() }, [])

  async function loadWorkspace() {
    setLoading(true)
    try {
      const [driverData, vehicleData, eligibleData, shipmentData, reportData, notificationData, userData] = await Promise.all([getDrivers(), getVehicles(), getEligibleShipmentOrders(), getShipments(), getShipmentReportsForReview(), getMyNotifications(), getUsers()])
      setDrivers(Array.isArray(driverData) ? driverData : [])
      setVehicles(Array.isArray(vehicleData) ? vehicleData : [])
      setEligibleOrders(Array.isArray(eligibleData) ? eligibleData : [])
      setShipments(Array.isArray(shipmentData) ? shipmentData : [])
      setShipmentReports(Array.isArray(reportData) ? reportData : [])
      setNotifications(Array.isArray(notificationData) ? notificationData : [])
      setUsers(Array.isArray(userData) ? userData : [])
      setError('')
    } catch (err) { setError(getErrorMessage(err, 'Không tải được shipping manager workspace.')) }
    finally { setLoading(false) }
  }
  function change(setter) { return (event) => { const { name, value } = event.target; setter((prev) => ({ ...prev, [name]: value })) } }
  async function submitShipment(event) { event.preventDefault(); setSavingShipment(true); setError(''); setSuccess(''); try { const created = await createShipment({ orderId: Number(shipmentForm.orderId), driverId: toPositiveNumber(shipmentForm.driverId), vehicleId: toPositiveNumber(shipmentForm.vehicleId), note: shipmentForm.note.trim() }); setSuccess('Đã tạo shipment và assign logistics resource.'); setShipmentForm(initialShipmentForm); setSelectedShipmentId(String(created.shipmentId)); await loadWorkspace() } catch (err) { setError(getErrorMessage(err, 'Không thể tạo shipment.')) } finally { setSavingShipment(false) } }
  async function submitDriver(event) { event.preventDefault(); setSavingDriver(true); setError(''); setSuccess(''); try { if (selectedDriverId) await updateDriver(Number(selectedDriverId), { licenseNo: driverForm.licenseNo.trim(), status: driverForm.status.trim() }); else await createDriver({ driverCode: driverForm.driverCode.trim(), licenseNo: driverForm.licenseNo.trim(), userId: toPositiveNumber(driverForm.userId), status: driverForm.status.trim() }); setSuccess(selectedDriverId ? 'Đã cập nhật driver.' : 'Đã tạo driver mới.'); setSelectedDriverId(''); setDriverForm(initialDriverForm); await loadWorkspace() } catch (err) { setError(getErrorMessage(err, 'Không thể lưu driver.')) } finally { setSavingDriver(false) } }
  async function submitVehicle(event) { event.preventDefault(); setSavingVehicle(true); setError(''); setSuccess(''); try { if (selectedVehicleId) await updateVehicle(Number(selectedVehicleId), { vehicleType: vehicleForm.vehicleType.trim(), capacity: Number(vehicleForm.capacity), status: vehicleForm.status.trim() }); else await createVehicle({ plateNo: vehicleForm.plateNo.trim(), vehicleType: vehicleForm.vehicleType.trim(), capacity: Number(vehicleForm.capacity), status: vehicleForm.status.trim() }); setSuccess(selectedVehicleId ? 'Đã cập nhật vehicle.' : 'Đã tạo vehicle mới.'); setSelectedVehicleId(''); setVehicleForm(initialVehicleForm); await loadWorkspace() } catch (err) { setError(getErrorMessage(err, 'Không thể lưu vehicle.')) } finally { setSavingVehicle(false) } }
  async function submitShipmentStatus(event) { event.preventDefault(); if (!selectedShipment) return; setSavingShipment(true); try { await updateShipmentStatus(selectedShipment.shipmentId, { status: shipmentStatusForm.status, note: shipmentStatusForm.note.trim() }); setSuccess('Đã cập nhật shipment.'); await loadWorkspace() } catch (err) { setError(getErrorMessage(err, 'Không thể cập nhật shipment.')) } finally { setSavingShipment(false) } }
  function fillDriver(driver) { setSelectedDriverId(String(driver.driverId)); setDriverForm({ driverCode: driver.driverCode || '', licenseNo: driver.licenseNo || '', userId: String(driver.userId || ''), status: driver.status || 'ACTIVE' }) }
  function fillVehicle(vehicle) { setSelectedVehicleId(String(vehicle.vehicleId)); setVehicleForm({ plateNo: vehicle.plateNo || '', vehicleType: vehicle.vehicleType || '', capacity: vehicle.capacity || '', status: vehicle.status || 'ACTIVE' }) }
  async function handleMarkRead(notificationId) { try { await markNotificationRead(notificationId); await loadWorkspace() } catch (err) { setError(getErrorMessage(err, 'Không đánh dấu notification được.')) } }

  const props = { module, loading, error, success, displayShipments, shipmentReports, displayDrivers, displayVehicles, eligibleOrders, activeDrivers, activeVehicles, availableUsers, notifications, shipmentForm, driverForm, vehicleForm, shipmentStatusForm, selectedShipment, selectedDriverId, selectedVehicleId, savingShipment, savingDriver, savingVehicle, setShipmentForm, setShipmentStatusForm, submitShipment, submitDriver, submitVehicle, submitShipmentStatus, fillDriver, fillVehicle, handleMarkRead, onShipmentChange: change(setShipmentForm), onDriverChange: change(setDriverForm), onVehicleChange: change(setVehicleForm), onShipmentStatusChange: change(setShipmentStatusForm), loadWorkspace }
  const pages = { overview: <OverviewPage {...props} />, orders: <OrdersPage {...props} />, create: <CreateShipmentPage {...props} />, tracking: <TrackingPage {...props} />, drivers: <DriversPage {...props} />, vehicles: <VehiclesPage {...props} />, notifications: <NotificationsPage {...props} />, reports: <ReportsPage {...props} /> }
  return <section className={`shipping-prototype-shell shipping-module-${module}`}>{pages[module] || pages.overview}</section>
}

function PageChrome({ eyebrow, title, subtitle, actions, children, error, success, loading }) { return <><div className="ship-page-head"><div><p>{eyebrow}</p><h2>{title}</h2><span>{subtitle}</span></div><div className="ship-actions">{actions}</div></div>{loading ? <div className="ship-alert neutral">Đang đồng bộ dữ liệu vận chuyển...</div> : null}{error ? <div className="ship-alert danger">{error}</div> : null}{success ? <div className="ship-alert success">{success}</div> : null}{children}</> }
function Metric({ icon, label, value, note, tone = 'green' }) { return <article className={`ship-metric ${tone}`}><div><Icon fill>{icon}</Icon><span>{note}</span></div><p>{label}</p><strong>{value}</strong></article> }
function OverviewPage(p) { const deliveredCount = p.displayShipments.filter((s)=>String(s.status).toUpperCase()==='DELIVERED').length; const delayedCount = p.displayShipments.filter((s)=>['REJECTED','DISPUTED','ESCALATED'].includes(String(s.status).toUpperCase())).length; return <PageChrome eyebrow="Shipping Manager" title="Tổng quan Vận chuyển" subtitle="Điều phối đơn hàng, đội xe, tài xế và cảnh báo vận hành." loading={p.loading} error={p.error} success={p.success} actions={<button onClick={p.loadWorkspace}><Icon>refresh</Icon>Làm mới</button>}><section className="ship-metrics"><Metric icon="inventory" label="Chờ phân bổ" value={p.eligibleOrders.length} note="Eligible orders" tone="blue"/><Metric icon="local_shipping" label="Đang vận chuyển" value={p.displayShipments.length} note="Shipments API" tone="amber"/><Metric icon="task_alt" label="Đã giao" value={deliveredCount} note="Delivered"/><Metric icon="warning" label="Cần xử lý" value={delayedCount} note="Exception states" tone="red"/><Metric icon="badge" label="Tài xế hoạt động" value={p.activeDrivers.length} note="Active drivers"/></section><div className="ship-overview-grid"><article className="ship-card ship-map-card"><div className="ship-card-head"><h3><Icon>map</Icon>Bản đồ theo dõi trực tuyến</h3><span className="live-pill"><i />{p.displayShipments.length} shipment</span></div><MapPanel shipments={p.displayShipments} /></article><aside className="ship-stack"><AlertsCard reports={p.shipmentReports} /><ActivityCard shipments={p.displayShipments} /></aside></div><PendingOrders orders={p.eligibleOrders} setShipmentForm={p.setShipmentForm} /></PageChrome> }
function MapPanel({ shipments = [] }) { const visible = shipments.slice(0, 2); return <div className="ship-map">{visible.map((s, index)=><div className={`map-marker ${index===0?'one':'two'}`} key={s.shipmentId}><Icon>local_shipping</Icon><b>{s.vehiclePlateNo || `Shipment #${s.shipmentId}`}</b><small>{s.status || 'UNKNOWN'}</small></div>)}{visible.length===0?<div className="map-marker one"><Icon>map</Icon><b>Chưa có shipment</b><small>Backend chưa trả về vị trí vận chuyển.</small></div>:null}<div className="map-controls"><button type="button">+</button><button type="button">−</button></div></div> }
function AlertsCard({ reports = [] }) { const openReports = reports.filter((r)=>String(r.status).toUpperCase()==='OPEN').slice(0,3); return <article className="ship-card"><div className="ship-card-head"><h3><Icon>emergency_home</Icon>Cảnh báo Vận hành</h3><span className="danger-pill">{openReports.length} OPEN</span></div>{openReports.length ? openReports.map((r,i)=><div className={`ship-warning w${i}`} key={r.reportId}><strong>{r.issueType || 'Issue report'}</strong><p>{r.description || `Shipment #${r.shipmentId}`}</p></div>) : <p>Không có issue report mở từ backend.</p>}</article> }
function ActivityCard({ shipments = [] }) { return <article className="ship-card"><h3>Hoạt động Gần đây</h3><div className="ship-timeline">{shipments.slice(0,3).map((s)=><div key={s.shipmentId}><i /><strong>Shipment #{s.shipmentId}</strong><p>{s.status || 'UNKNOWN'} · {s.updatedAt || s.createdAt || 'No timestamp'}</p></div>)}{shipments.length===0?<p>Chưa có hoạt động shipment từ backend.</p>:null}</div></article> }
function PendingOrders({ orders, setShipmentForm }) { const list = safeList(orders); return <article className="ship-card"><div className="ship-card-head"><h3>Đơn hàng Chờ Phân bổ</h3><a href="/shipping/create">Tạo shipment</a></div>{list.length ? <div className="ship-table-wrap"><table className="ship-table"><thead><tr><th>Mã đơn</th><th>Điểm xuất phát</th><th>Điểm đến</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody>{list.map(o=><tr key={o.orderId}><td>#{o.orderId}</td><td>{o.farmName || 'Farm'}</td><td>{o.retailerName || 'Retailer'}</td><td><Status value={o.orderStatus} /></td><td><button onClick={()=>setShipmentForm(prev=>({...prev, orderId:String(o.orderId)}))}>Chọn</button></td></tr>)}</tbody></table></div> : <p>Không có order đủ điều kiện tạo shipment.</p>}</article> }
function OrdersPage(p) { const unassigned = p.displayShipments.filter((s)=>!s.driverCode).length; const exceptions = p.displayShipments.filter((s)=>['REJECTED','DISPUTED','ESCALATED'].includes(String(s.status).toUpperCase())).length; return <PageChrome eyebrow="Shipping / Orders" title="Quản lý Đơn vận chuyển" subtitle="Phân bổ tài xế và theo dõi tiến độ vận hành theo thời gian thực." loading={p.loading} error={p.error} success={p.success}><section className="ship-metrics four"><Metric icon="package_2" label="Tổng shipment" value={p.displayShipments.length} note="API"/><Metric icon="local_shipping" label="Đang giao" value={p.displayShipments.filter((s)=>['ASSIGNED','PICKED_UP','IN_TRANSIT'].includes(String(s.status).toUpperCase())).length} note="Active" tone="blue"/><Metric icon="pending_actions" label="Chưa gán tài xế" value={unassigned} note="Chờ xử lý" tone="amber"/><Metric icon="warning" label="Exception" value={exceptions} note="Cần xử lý" tone="red"/></section><article className="ship-card"><div className="ship-tabs"><button>Tất cả</button><button>Chờ xử lý</button><button>Đang vận chuyển</button><button>Đã hoàn thành</button></div><ShipmentTable shipments={p.displayShipments} /></article><VerificationHub shipments={p.displayShipments} /></PageChrome> }
function ShipmentTable({ shipments }) { if (!shipments.length) return <p>Chưa có shipment từ backend.</p>; return <div className="ship-table-wrap"><table className="ship-table large"><thead><tr><th>Shipment ID</th><th>Origin</th><th>Destination</th><th>Driver & Vehicle</th><th>Status</th><th>Updated</th><th>Actions</th></tr></thead><tbody>{shipments.map((s)=><tr key={s.shipmentId}><td><b>#{s.shipmentId}</b><small>Order #{s.orderId || 'N/A'}</small></td><td>{s.farmName || 'Nông trại'}</td><td>{s.retailerName || 'Retailer'}</td><td>{s.driverCode ? `${s.driverCode} • ${s.vehiclePlateNo || 'N/A'}` : <button className="dash-btn">Assign Driver</button>}</td><td><Status value={s.status} /></td><td>{s.updatedAt || s.createdAt || 'N/A'}</td><td><button><Icon>more_vert</Icon></button></td></tr>)}</tbody></table></div> }
function CreateShipmentPage(p) { return <PageChrome eyebrow="Shipping / Orders / New Shipment" title="Lập Lệnh Vận chuyển" subtitle="Configure logistics and blockchain verification for agricultural orders." loading={p.loading} error={p.error} success={p.success}><form className="ship-create-grid" onSubmit={p.submitShipment}><div className="ship-form-stack"><FormSection step="1" title="Order Identification"><label>Related Order<select name="orderId" value={p.shipmentForm.orderId} onChange={p.onShipmentChange} required><option value="">Chọn order</option>{safeList(p.eligibleOrders).map(o=><option key={o.orderId} value={o.orderId}>#{o.orderId} • {o.farmName} → {o.retailerName}</option>)}</select></label></FormSection><FormSection step="2" title="Logistics Nodes"><div className="node-card"><Icon>location_on</Icon><input value={p.eligibleOrders.find(o=>String(o.orderId)===String(p.shipmentForm.orderId))?.farmName || ''} readOnly placeholder="Origin resolved from selected order" /></div><div className="node-line"/><div className="node-card"><Icon>local_shipping</Icon><input value={p.eligibleOrders.find(o=>String(o.orderId)===String(p.shipmentForm.orderId))?.retailerName || ''} readOnly placeholder="Destination resolved from selected order" /></div></FormSection><FormSection step="3" title="Scheduling & Resources"><div className="two-cols"><label>Driver<select name="driverId" value={p.shipmentForm.driverId} onChange={p.onShipmentChange}><option value="">Chọn driver</option>{p.activeDrivers.map(d=><option key={d.driverId} value={d.driverId}>{d.driverCode} • {d.userFullName}</option>)}</select></label><label>Vehicle<select name="vehicleId" value={p.shipmentForm.vehicleId} onChange={p.onShipmentChange}><option value="">Chọn vehicle</option>{p.activeVehicles.map(v=><option key={v.vehicleId} value={v.vehicleId}>{v.plateNo} • {v.vehicleType}</option>)}</select></label></div></FormSection><FormSection title="Special Instructions"><textarea name="note" value={p.shipmentForm.note} onChange={p.onShipmentChange} placeholder="Mention handling requirements, temperature thresholds, or ledger notes..." /></FormSection></div><aside className="ship-summary"><MapPanel shipments={p.displayShipments} /><div className="protocol-card"><Icon fill>verified_user</Icon><h3>Backend Verification</h3><p>Shipment evidence is committed by the backend after successful creation and status updates.</p><small>HASH: assigned by API / blockchain service</small></div><button className="primary-action" disabled={p.savingShipment}><Icon>send</Icon>{p.savingShipment?'Đang tạo...':'Confirm & Create Shipment'}</button><button type="button" className="secondary-action">Clear form</button></aside></form></PageChrome> }
function FormSection({ step, title, children }) { return <article className="ship-card form-section"><h3>{step ? <span>{step}</span> : <Icon>notes</Icon>}{title}</h3>{children}</article> }
function TrackingPage(p) { return <PageChrome eyebrow="Shipping / Tracking" title="Theo dõi Hành trình" subtitle="Live shipment status from backend." loading={p.loading} error={p.error} success={p.success}><div className="tracking-layout"><div className="tracking-map"><MapPanel shipments={p.displayShipments} /><div className="tracking-stats"><Metric icon="check_circle" label="Delivered" value={p.displayShipments.filter((s)=>String(s.status).toUpperCase()==='DELIVERED').length} note="API"/><Metric icon="sensors" label="Active Units" value={p.displayShipments.length} note="LIVE" tone="blue"/></div></div><aside className="tracking-list"><h3>Lô hàng đang đi <span className="live-pill"><i/>LIVE</span></h3>{p.displayShipments.length ? p.displayShipments.map((s,i)=><div className={`tracking-card ${i===0?'active':''}`} key={s.shipmentId}><strong>Shipment #{s.shipmentId}</strong><p>{s.farmName} → {s.retailerName}</p><div className="progress"><i style={{width:String(s.status).toUpperCase()==='DELIVERED'?'100%':String(s.status).toUpperCase()==='IN_TRANSIT'?'68%':'35%'}} /></div><Status value={s.status}/></div>) : <p>Chưa có shipment active để theo dõi.</p>}</aside></div></PageChrome> }
function DriversPage(p) { return <PageChrome eyebrow="Shipping / Drivers" title="Quản lý Tài xế" subtitle={`${p.displayDrivers.length} tài xế trong mạng lưới • ${p.activeDrivers.length} đang hoạt động`} loading={p.loading} error={p.error} success={p.success}><section className="ship-metrics four"><Metric icon="group" label="Tổng số tài xế" value={p.displayDrivers.length} note="API"/><Metric icon="radio_button_checked" label="Đang hoạt động" value={p.activeDrivers.length} note="ACTIVE"/><Metric icon="star" label="Đã gán shipment" value={p.displayShipments.filter((s)=>s.driverCode).length} note="Assignments" tone="amber"/><Metric icon="task_alt" label="Đã giao" value={p.displayShipments.filter((s)=>String(s.status).toUpperCase()==='DELIVERED').length} note="Delivered" tone="blue"/></section><div className="drivers-grid"><article className="ship-card"><DriverTable drivers={p.displayDrivers} fillDriver={p.fillDriver}/></article><DriverForm {...p}/></div><article className="ship-card"><h3>Bản đồ Tài xế thời gian thực</h3><MapPanel shipments={p.displayShipments} /></article></PageChrome> }
function DriverTable({ drivers, fillDriver }) { if (!drivers.length) return <p>Chưa có driver từ backend.</p>; return <div className="ship-table-wrap"><table className="ship-table"><thead><tr><th>Tài xế</th><th>Liên hệ</th><th>Trạng thái</th><th>Đơn hiện tại</th><th>Đánh giá</th><th></th></tr></thead><tbody>{drivers.map(d=><tr key={d.driverId}><td><b>{d.userFullName || d.driverCode}</b><small>ID: {d.driverId}</small></td><td>{d.phone || 'N/A'}<small>{d.email || d.driverCode || ''}</small></td><td><Status value={d.status}/></td><td><div className="progress"><i style={{width:d.status==='ACTIVE'?'75%':'30%'}}/></div></td><td>{d.rating || 'N/A'}</td><td><button onClick={()=>fillDriver(d)}><Icon>edit</Icon></button></td></tr>)}</tbody></table></div> }
function DriverForm(p) { return <article className="ship-card"><h3>{p.selectedDriverId ? 'Cập nhật tài xế' : 'Thêm tài xế mới'}</h3><form className="ship-form" onSubmit={p.submitDriver}><input name="driverCode" placeholder="Driver code" value={p.driverForm.driverCode} onChange={p.onDriverChange} disabled={Boolean(p.selectedDriverId)} required/><input name="licenseNo" placeholder="License number" value={p.driverForm.licenseNo} onChange={p.onDriverChange} required/><select name="userId" value={p.driverForm.userId} onChange={p.onDriverChange} disabled={Boolean(p.selectedDriverId)}><option value="">Chọn user</option>{p.availableUsers.map(u=><option key={u.userId} value={u.userId}>{u.fullName} • {u.email}</option>)}</select><input name="status" value={p.driverForm.status} onChange={p.onDriverChange}/><button disabled={p.savingDriver}>{p.savingDriver?'Đang lưu...':'Lưu tài xế'}</button></form></article> }
function VehiclesPage(p) { return <PageChrome eyebrow="Shipping / Vehicles" title="Quản lý Phương tiện" subtitle="Biển số, tải trọng, trạng thái vận hành." loading={p.loading} error={p.error} success={p.success}><div className="drivers-grid"><article className="ship-card"><div className="ship-table-wrap"><table className="ship-table"><thead><tr><th>Biển số</th><th>Loại xe</th><th>Tải trọng</th><th>Trạng thái</th><th></th></tr></thead><tbody>{p.displayVehicles.map(v=><tr key={v.vehicleId}><td><b>{v.plateNo}</b></td><td>{v.vehicleType}</td><td>{formatCapacity(v.capacity)}</td><td><Status value={v.status}/></td><td><button onClick={()=>p.fillVehicle(v)}><Icon>edit</Icon></button></td></tr>)}{p.displayVehicles.length===0?<tr><td colSpan="5">Chưa có vehicle từ backend.</td></tr>:null}</tbody></table></div></article><article className="ship-card"><h3>{p.selectedVehicleId?'Cập nhật vehicle':'Tạo vehicle'}</h3><form className="ship-form" onSubmit={p.submitVehicle}><input name="plateNo" placeholder="Plate number" value={p.vehicleForm.plateNo} onChange={p.onVehicleChange} disabled={Boolean(p.selectedVehicleId)} required/><input name="vehicleType" placeholder="Vehicle type" value={p.vehicleForm.vehicleType} onChange={p.onVehicleChange} required/><input name="capacity" type="number" placeholder="Capacity" value={p.vehicleForm.capacity} onChange={p.onVehicleChange} required/><input name="status" value={p.vehicleForm.status} onChange={p.onVehicleChange}/><button disabled={p.savingVehicle}>Lưu vehicle</button></form></article></div></PageChrome> }
function NotificationsPage(p) { return <PageChrome eyebrow="Shipping / Notifications" title="Thông báo logistics" subtitle="Nhận/gửi thông tin thay đổi shipment." loading={p.loading} error={p.error} success={p.success}><article className="ship-card">{p.notifications.length===0?<p>Chưa có notification.</p>:p.notifications.map(n=><div className="notification-row" key={n.notificationId}><div><strong>{n.title}</strong><p>{n.message}</p></div>{!n.read?<button onClick={()=>p.handleMarkRead(n.notificationId)}>Đánh dấu đọc</button>:<Status value="READ"/>}</div>)}</article></PageChrome> }
function ReportsPage(p) { const reports = safeList(p.shipmentReports); return <PageChrome eyebrow="Shipping / Reports" title="Báo cáo vận hành" subtitle="Driver issue inbox, proof, QR scan và SLA." loading={p.loading} error={p.error} success={p.success} actions={<button onClick={p.loadWorkspace}><Icon>refresh</Icon>Làm mới</button>}><VerificationHub shipments={p.displayShipments} /><article className="ship-card"><div className="ship-card-head"><h3>Driver Issue Inbox</h3><span className="danger-pill">{reports.filter((r)=>String(r.status).toUpperCase()==='OPEN').length} OPEN</span></div>{reports.length ? <div className="ship-table-wrap"><table className="ship-table"><thead><tr><th>Report</th><th>Shipment</th><th>Driver</th><th>Issue</th><th>Severity</th><th>Status</th></tr></thead><tbody>{reports.map((r)=><tr key={r.reportId}><td><b>#{r.reportId}</b><small>{r.description || 'Không có mô tả'}</small></td><td>#{r.shipmentId}</td><td>{r.driverId || 'N/A'}</td><td>{r.issueType}</td><td><Status value={r.severity}/></td><td><Status value={r.status}/></td></tr>)}</tbody></table></div> : <p>Chưa có driver issue report từ backend.</p>}</article></PageChrome> }
function VerificationHub({ shipments = [] }) { const latest = shipments[0]; return <section className="verification-grid"><article className="ship-card"><h3><Icon fill>verified_user</Icon>Verification Hub</h3><div className="ship-timeline"><div><i/><strong>Selected shipment</strong><p>{latest ? `Shipment #${latest.shipmentId} · ${latest.status}` : 'No shipment selected from backend'}</p></div><div><i/><strong>Order reference</strong><p>{latest?.orderId ? `Order #${latest.orderId}` : 'N/A'}</p></div><div><i/><strong>Trace evidence</strong><p>{latest?.blockchainTxHash || latest?.txHash || 'Awaiting backend/blockchain proof'}</p></div></div></article><article className="ship-card image-card"><span>LIVE OPS</span><h3>Fleet Management Dashboard</h3><p>Giám sát đội xe bằng dữ liệu shipment, report và notification từ backend.</p></article></section> }
