const EXACT_REPAIRS = new Map([
  ['Farm / Sáº£n xuáº¥t / MĂ¹a v?', 'Farm / Sáº£n xuáº¥t / MĂ¹a vá»¥'],
  ['FARM / Sáº¢N XUáº¤T / MĂ™A V?', 'FARM / Sáº¢N XUáº¤T / MĂ™A Vá»¤'],
  ['Quáº£n lĂ½ MĂ¹a v? & Quy tr?nh canh tĂ¡c', 'Quáº£n lĂ½ mĂ¹a vá»¥ & quy trĂ¬nh canh tĂ¡c'],
  ['3 mĂ¹a v? â€¢ 0 Ä‘ang tr?ng â€¢ 3 Ä‘Ă£ thu ho?ch â€¢ Click 1 dĂ²ng Ä‘á»ƒ xem chi ti?t, blockchain proof, timeline quy tr?nh', '3 mĂ¹a vá»¥ â€¢ 0 Ä‘ang trá»“ng â€¢ 3 Ä‘Ă£ thu hoáº¡ch â€¢ Click 1 dĂ²ng Ä‘á»ƒ xem chi tiáº¿t, blockchain proof, timeline quy trĂ¬nh'],
  ['Tá»•ng s? mĂ¹a v?', 'Tá»•ng sá»‘ mĂ¹a vá»¥'],
  ['ÄĂ£ lĂªn k? ho?ch', 'ÄĂ£ lĂªn káº¿ hoáº¡ch'],
  ['Äang tr?ng', 'Äang trá»“ng'],
  ['ÄĂ£ thu ho?ch', 'ÄĂ£ thu hoáº¡ch'],
  ['Danh sĂ¡ch mĂ¹a v?', 'Danh sĂ¡ch mĂ¹a vá»¥'],
  ['M? MĂ™A V?', 'MĂƒ MĂ™A Vá»¤'],
  ['B?T Äáº¦U', 'Báº®T Äáº¦U'],
  ['THU HOáº CH D? KI?N', 'THU HOáº CH Dá»° KIáº¾N'],
  ['T?o mĂ¹a v? má»›i', 'Táº¡o mĂ¹a vá»¥ má»›i'],
  ['M? mĂ¹a v?', 'MĂ£ mĂ¹a vá»¥'],
  ['M? Ä‘á»‹nh danh duy nh?t cho mĂ¹a v?. H? th?ng Ä‘á» xu?t s?n theo m? farm + ngĂ y, b?n cĂ³ th? Ä‘á»•i.', 'MĂ£ Ä‘á»‹nh danh duy nháº¥t cho mĂ¹a vá»¥. Há»‡ thá»‘ng Ä‘á» xuáº¥t sáºµn theo mĂ£ farm + ngĂ y, báº¡n cĂ³ thá»ƒ Ä‘á»•i.'],
  ['Farm / Sáº£n xuáº¥t / LĂ´ hĂ ng', 'Farm / Sáº£n xuáº¥t / LĂ´ hĂ ng'],
  ['FARM / Sáº¢N XUáº¤T / LĂ” HĂ€NG', 'FARM / Sáº¢N XUáº¤T / LĂ” HĂ€NG'],
  ['Quáº£n lĂ½ LĂ´ hĂ ng', 'Quáº£n lĂ½ lĂ´ hĂ ng'],
  ['3 lĂ´ â€¢ 3 s?n sĂ ng â€¢ 0 Ä‘Ă£ bĂ¡n h?t â€¢ 1.550 kg cĂ²n l?i', '3 lĂ´ â€¢ 3 sáºµn sĂ ng â€¢ 0 Ä‘Ă£ bĂ¡n háº¿t â€¢ 1.550 kg cĂ²n láº¡i'],
  ['Tá»•ng s? lĂ´', 'Tá»•ng sá»‘ lĂ´'],
  ['S?n sĂ ng bĂ¡n', 'Sáºµn sĂ ng bĂ¡n'],
  ['ÄĂ£ bĂ¡n h?t', 'ÄĂ£ bĂ¡n háº¿t'],
  ['Kh? d?ng (kg)', 'Kháº£ dá»¥ng (kg)'],
  ['T?o lĂ´ hĂ ng', 'Táº¡o lĂ´ hĂ ng'],
  ['MĂ¹a v? *', 'MĂ¹a vá»¥ *'],
  ['â€” Ch?n mĂ¹a v? â€”', 'â€” Chá»n mĂ¹a vá»¥ â€”'],
  ['LĂ´ hĂ ng Ä‘Æ°á»£c t?o t? mĂ¹a v? Ä‘Ă£ thu ho?ch.', 'LĂ´ hĂ ng Ä‘Æ°á»£c táº¡o tá»« mĂ¹a vá»¥ Ä‘Ă£ thu hoáº¡ch.'],
  ['M? lĂ´ hĂ ng', 'MĂ£ lĂ´ hĂ ng'],
  ['M? Ä‘á»‹nh danh duy nh?t cho lĂ´ hĂ ng.', 'MĂ£ Ä‘á»‹nh danh duy nháº¥t cho lĂ´ hĂ ng.'],
  ['M? BATCH', 'MĂƒ BATCH'],
  ['MĂ™A V?', 'MĂ™A Vá»¤'],
  ['S? LÆ¯á»¢NG (CĂ’N / Tá»”NG)', 'Sá» LÆ¯á»¢NG (CĂ’N / Tá»”NG)'],
  ['TR?NG THĂI', 'TRáº NG THĂI'],
  ['Farm / Sáº£n xuáº¥t / Xu?t QR & Truy xu?t', 'Farm / Sáº£n xuáº¥t / Xuáº¥t QR & Truy xuáº¥t'],
  ['FARM / Sáº¢N XUáº¤T / XU?T QR & TRUY XUáº¤T', 'FARM / Sáº¢N XUáº¤T / XUáº¤T QR & TRUY XUáº¤T'],
  ['Xu?t mĂ¹a v?, M? QR & Truy xuáº¥t nguá»“n gá»‘c', 'Xuáº¥t mĂ¹a vá»¥, mĂ£ QR & truy xuáº¥t nguá»“n gá»‘c'],
  ['3 mĂ¹a v? s?n sĂ ng xu?t â€¢ 3 Ä‘Ă£ xu?t â€¢ 3/3 batch Ä‘Ă£ cĂ³ QR', '3 mĂ¹a vá»¥ sáºµn sĂ ng xuáº¥t â€¢ 3 Ä‘Ă£ xuáº¥t â€¢ 3/3 batch Ä‘Ă£ cĂ³ QR'],
  ['MĂ¹a v? cĂ³ th? xu?t', 'MĂ¹a vá»¥ cĂ³ thá»ƒ xuáº¥t'],
  ['ÄĂ£ xu?t', 'ÄĂ£ xuáº¥t'],
  ['Äang xem trace', 'Äang xem trace'],
  ['Xu?t mĂ¹a v?', 'Xuáº¥t mĂ¹a vá»¥'],
  ['M? mĂ¹a v?', 'MĂ£ mĂ¹a vá»¥'],
  ['Xu?t lá»—i', 'Xuáº¥t lá»—i'],
  ['Xu?t l?i', 'Xuáº¥t láº¡i'],
  ['ChÆ°a xu?t', 'ChÆ°a xuáº¥t'],
  ['M? QR', 'MĂ£ QR'],
  ['Truy xu?t nguá»“n gá»‘c', 'Truy xuáº¥t nguá»“n gá»‘c'],
  ['Theo dĂµi sáº£n xuáº¥t, IoT vĂ  chuá»—i cung ?ng theo thá»i gian th?c.', 'Theo dĂµi sáº£n xuáº¥t, IoT vĂ  chuá»—i cung á»©ng theo thá»i gian thá»±c.'],
  ['Tá»•ng MĂ¹a V?', 'Tá»•ng mĂ¹a vá»¥'],
  ['Tá»•ng LĂ´ HĂ ng', 'Tá»•ng lĂ´ hĂ ng'],
  ['ÄÆ¡n Ch? X? L?', 'ÄÆ¡n chá» xá»­ lĂ½'],
  ['Äang Giao HĂ ng', 'Äang giao hĂ ng'],
  ['S?n lÆ°á»£ng thu ho?ch Â· 6 thĂ¡ng', 'Sáº£n lÆ°á»£ng thu hoáº¡ch Â· 6 thĂ¡ng'],
  ['S?n lÆ°á»£ng thu ho?ch Â· 6 thÄ‚Â¡ng', 'Sáº£n lÆ°á»£ng thu hoáº¡ch Â· 6 thĂ¡ng'],
  ['Xem chi ti?t', 'Xem chi tiáº¿t'],
  ['C?nh bĂ¡o IoT', 'Cáº£nh bĂ¡o IoT'],
  ['Cáº£nh bĂ¡o IoT', 'Cáº£nh bĂ¡o IoT'],
  ['KhĂ´ng cĂ³ cáº£nh bĂ¡o IoT Ä‘ang m?.', 'KhĂ´ng cĂ³ cáº£nh bĂ¡o IoT Ä‘ang má»Ÿ.'],
  ['C?u hĂ¬nh ngÆ°á»¡ng cáº£nh bĂ¡o', 'Cáº¥u hĂ¬nh ngÆ°á»¡ng cáº£nh bĂ¡o'],
  ['Äáº·t ngÆ°á»¡ng nhi?t Ä‘á»™, Ä‘á»™ ?m, pH theo mĂ¹a v? vĂ  xem bĂ¡o cĂ¡o v?n chuy?n t? tĂ i x?.', 'Äáº·t ngÆ°á»¡ng nhiá»‡t Ä‘á»™, Ä‘á»™ áº©m, pH theo mĂ¹a vá»¥ vĂ  xem bĂ¡o cĂ¡o váº­n chuyá»ƒn tá»« tĂ i xáº¿.'],
  ['BĂ¡o cĂ¡o v?n chuy?n', 'BĂ¡o cĂ¡o váº­n chuyá»ƒn'],
  ['ÄÆ¡n hĂ ng t? retailer', 'ÄÆ¡n hĂ ng tá»« retailer'],
  ['ThĂ´ng tin cĂ¡ nhĂ¢n ch? s? h?u', 'ThĂ´ng tin cĂ¡ nhĂ¢n chá»§ sá»Ÿ há»¯u'],
  ['H? vĂ  tĂªn', 'Há» vĂ  tĂªn'],
  ['Sá»‘ Ä‘iá»‡n tho?i', 'Sá»‘ Ä‘iá»‡n thoáº¡i'],
  ['Vai tr?', 'Vai trĂ²'],
  ['ThĂ´ng tin nĂ´ng tr?i', 'ThĂ´ng tin nĂ´ng tráº¡i'],
  ['M? farm', 'MĂ£ farm'],
  ['Lo?i hĂ¬nh', 'Loáº¡i hĂ¬nh'],
  ['Sá»‘ gi?y phĂ©p kinh doanh', 'Sá»‘ giáº¥y phĂ©p kinh doanh'],
  ['Äá»‹a ch?', 'Äá»‹a chá»‰'],
  ['T?nh / TP', 'Tá»‰nh / TP'],
  ['Di?n tĂ­ch (ha)', 'Diá»‡n tĂ­ch (ha)'],
  ['NgÆ°á»i liĂªn h?', 'NgÆ°á»i liĂªn há»‡'],
  ['MĂ´ t?', 'MĂ´ táº£'],
  ['B?o m?t', 'Báº£o máº­t'],
  ['M?t kh?u hi?n t?i', 'Máº­t kháº©u hiá»‡n táº¡i'],
  ['M?t kh?u má»›i', 'Máº­t kháº©u má»›i'],
  ['XĂ¡c nháº­n m?t kh?u', 'XĂ¡c nháº­n máº­t kháº©u'],
  ['Äá»•i m?t kh?u', 'Äá»•i máº­t kháº©u'],
  ['Tráº¡ng thĂ¡i Farm', 'Tráº¡ng thĂ¡i Farm'],
  ['GĂ³i dá»‹ch v? & Thanh toĂ¡n', 'GĂ³i dá»‹ch vá»¥ & Thanh toĂ¡n'],
  ['BICAP cung c?p cĂ¡c gĂ³i dá»‹ch v? Ä‘á»ƒ Farm s? d?ng n?n t?ng. Qu?n tr? viĂªn BICAP Ä‘á»‹nh giĂ¡; b?n ch?n gĂ³i vĂ  thanh toĂ¡n qua c?ng.', 'BICAP cung cáº¥p cĂ¡c gĂ³i dá»‹ch vá»¥ Ä‘á»ƒ Farm sá»­ dá»¥ng ná»n táº£ng. Quáº£n trá»‹ viĂªn BICAP Ä‘á»‹nh giĂ¡; báº¡n chá»n gĂ³i vĂ  thanh toĂ¡n qua cá»•ng.'],
  ['Sub ch? thanh toĂ¡n', 'Sub chá» thanh toĂ¡n'],
  ['L?ch s? thanh toĂ¡n', 'Lá»‹ch sá»­ thanh toĂ¡n'],
  ['GĂ³i Ä‘ang ho?t Ä‘á»™ng', 'GĂ³i Ä‘ang hoáº¡t Ä‘á»™ng'],
  ['M? SUBSCRIPTION', 'MĂ£ subscription'],
  ['HI?U L?C', 'HIá»†U Lá»°C'],
  ['NĂ¢ng c?p / Gia h?n gĂ³i', 'NĂ¢ng cáº¥p / Gia háº¡n gĂ³i'],
  ['GĂ³i hi?n t?i:', 'GĂ³i hiá»‡n táº¡i:'],
  ['h?t h?n', 'háº¿t háº¡n'],
  ['GĂ³i catalogue', 'GĂ³i catalogue'],
  ['Tráº¡ng thĂ¡i', 'Tráº¡ng thĂ¡i'],
  ['Farm / Sáº£n xuáº¥t / MĂ¹a v?', 'Farm / Sáº£n xuáº¥t / MĂ¹a vá»¥'],
  ['Quáº£n lĂ½ MĂ¹a v? & Quy tr?nh canh tĂ¡c', 'Quáº£n lĂ½ mĂ¹a vá»¥ & quy trĂ¬nh canh tĂ¡c'],
  ['3 mĂ¹a v? â€¢ 0 Ä‘ang tr?ng â€¢ 3 Ä‘Ă£ thu ho?ch â€¢ Click 1 d?ng Ä‘á»ƒ xem chi ti?t, blockchain proof, timeline quy tr?nh', '3 mĂ¹a vá»¥ â€¢ 0 Ä‘ang trá»“ng â€¢ 3 Ä‘Ă£ thu hoáº¡ch â€¢ Click 1 dĂ²ng Ä‘á»ƒ xem chi tiáº¿t, blockchain proof, timeline quy trĂ¬nh'],
  ['Tá»•ng s? mĂ¹a v?', 'Tá»•ng sá»‘ mĂ¹a vá»¥'],
  ['ÄĂ£ lĂªn k? ho?ch', 'ÄĂ£ lĂªn káº¿ hoáº¡ch'],
  ['Äang tr?ng', 'Äang trá»“ng'],
  ['ÄĂ£ thu ho?ch', 'ÄĂ£ thu hoáº¡ch'],
  ['Danh sĂ¡ch mĂ¹a v?', 'Danh sĂ¡ch mĂ¹a vá»¥'],
  ['M? MĂ™A V?', 'MĂ£ mĂ¹a vá»¥'],
  ['B?T Äáº¦U', 'Báº¯t Ä‘áº§u'],
  ['THU HOáº CH D? KI?N', 'Thu hoáº¡ch dá»± kiáº¿n'],
  ['T?o mĂ¹a v? má»›i', 'Táº¡o mĂ¹a vá»¥ má»›i'],
  ['M? mĂ¹a v?', 'MĂ£ mĂ¹a vá»¥'],
  ['M? Ä‘á»‹nh danh duy nh?t cho mĂ¹a v?. H? th?ng Ä‘á» xu?t s?n theo m? farm + ngĂ y, b?n cĂ³ th? Ä‘á»•i.', 'MĂ£ Ä‘á»‹nh danh duy nháº¥t cho mĂ¹a vá»¥. Há»‡ thá»‘ng Ä‘á» xuáº¥t sáºµn theo mĂ£ farm + ngĂ y, báº¡n cĂ³ thá»ƒ Ä‘á»•i.'],
  ['Sáº£n pháº©m canh tĂ¡c', 'Sáº£n pháº©m canh tĂ¡c'],
  ['Farm / Sáº£n xuáº¥t / LĂ´ hĂ ng', 'Farm / Sáº£n xuáº¥t / LĂ´ hĂ ng'],
  ['Quáº£n lĂ½ LĂ´ hĂ ng', 'Quáº£n lĂ½ lĂ´ hĂ ng'],
  ['3 lĂ´ â€¢ 3 s?n sĂ ng â€¢ 0 Ä‘Ă£ bĂ¡n h?t â€¢ 1.550 kg cĂ²n l?i', '3 lĂ´ â€¢ 3 sáºµn sĂ ng â€¢ 0 Ä‘Ă£ bĂ¡n háº¿t â€¢ 1.550 kg cĂ²n láº¡i'],
  ['Tá»•ng s? lĂ´', 'Tá»•ng sá»‘ lĂ´'],
  ['S?n sĂ ng bĂ¡n', 'Sáºµn sĂ ng bĂ¡n'],
  ['ÄĂ£ bĂ¡n h?t', 'ÄĂ£ bĂ¡n háº¿t'],
  ['Kh? d?ng (kg)', 'Kháº£ dá»¥ng (kg)'],
  ['M? BATCH', 'MĂ£ batch'],
  ['MĂ™A V?', 'MĂ¹a vá»¥'],
  ['S? LÆ¯á»¢NG (Cáº¦N / Tá»”NG)', 'Sá»‘ lÆ°á»£ng (cĂ²n / tá»•ng)'],
  ['T?o lĂ´ hĂ ng', 'Táº¡o lĂ´ hĂ ng'],
  ['â€” Ch?n mĂ¹a v? â€”', 'â€” Chá»n mĂ¹a vá»¥ â€”'],
  ['LĂ´ hĂ ng Ä‘Æ°á»£c t?o t? mĂ¹a v? Ä‘Ă£ thu ho?ch.', 'LĂ´ hĂ ng Ä‘Æ°á»£c táº¡o tá»« mĂ¹a vá»¥ Ä‘Ă£ thu hoáº¡ch.'],
  ['M? lĂ´ hĂ ng', 'MĂ£ lĂ´ hĂ ng'],
  ['M? Ä‘á»‹nh danh duy nh?t cho lĂ´ hĂ ng.', 'MĂ£ Ä‘á»‹nh danh duy nháº¥t cho lĂ´ hĂ ng.'],
  ['NgĂ y thu ho?ch', 'NgĂ y thu hoáº¡ch'],
  ['H?n s? d?ng', 'Háº¡n sá»­ dá»¥ng'],
  ['Farm / Sáº£n xuáº¥t / Xu?t QR & Truy xuáº¥t', 'Farm / Sáº£n xuáº¥t / Xuáº¥t QR & truy xuáº¥t'],
  ['Xu?t mĂ¹a v?, M? QR & Truy xuáº¥t nguá»“n gá»‘c', 'Xuáº¥t mĂ¹a vá»¥, mĂ£ QR & truy xuáº¥t nguá»“n gá»‘c'],
  ['3 mĂ¹a v? s?n sĂ ng xu?t â€¢ 3 Ä‘Ă£ xu?t â€¢ 3/3 batch Ä‘Ă£ cĂ³ QR', '3 mĂ¹a vá»¥ sáºµn sĂ ng xuáº¥t â€¢ 3 Ä‘Ă£ xuáº¥t â€¢ 3/3 batch Ä‘Ă£ cĂ³ QR'],
  ['MĂ¹a v? cĂ³ th? xu?t', 'MĂ¹a vá»¥ cĂ³ thá»ƒ xuáº¥t'],
  ['ÄĂ£ xu?t', 'ÄĂ£ xuáº¥t'],
  ['Xu?t mĂ¹a v?', 'Xuáº¥t mĂ¹a vá»¥'],
  ['M? mĂ¹a v?', 'MĂ£ mĂ¹a vá»¥'],
  ['Xu?t lá»—i', 'Xuáº¥t lá»—i'],
  ['Xu?t l?i', 'Xuáº¥t láº¡i'],
  ['Xu?t + Sinh QR', 'Xuáº¥t + sinh QR'],
  ['S?N XUáº¤T', 'Sáº¢N XUáº¤T'],
  ['S?N PHáº¨M', 'Sáº¢N PHáº¨M'],
  ['B?T Äáº¦U', 'Báº®T Äáº¦U'],
  ['S? LÆ¯á»¢NG (Cáº¦N / Tá»”NG)', 'Sá» LÆ¯á»¢NG (CĂ’N / Tá»”NG)'],
  ['cáº§n lá»—i', 'cĂ²n láº¡i'],
  ['cáºµn lá»—i', 'cĂ²n láº¡i'],
  ['c?n l?i', 'cĂ²n láº¡i'],
  ['MĂ¹a vá»¥ cĂ³ thá»ƒ xuáº¥t', 'MĂ¹a vá»¥ cĂ³ thá»ƒ xuáº¥t'],
  ['Äang t?i d? li?u', 'Äang táº£i dá»¯ liá»‡u'],
  ['BICAP Ä‘ang Ä‘á»“ng b? d? li?u m?i nh?t...', 'BICAP Ä‘ang Ä‘á»“ng bá»™ dá»¯ liá»‡u má»›i nháº¥t...'],
  ['Äang x? l?', 'Äang xá»­ lĂ½'],
  ['KhĂ´ng th? t?i d? li?u', 'KhĂ´ng thá»ƒ táº£i dá»¯ liá»‡u'],
  ['C?n ki?m tra', 'Cáº§n kiá»ƒm tra'],
  ['Vui l?ng th? l?i ho?c ki?m tra k?t n?i t?i backend.', 'Vui lĂ²ng thá»­ láº¡i hoáº·c kiá»ƒm tra káº¿t ná»‘i tá»›i backend.'],
  ['ChÆ°a cĂ³ d? li?u', 'ChÆ°a cĂ³ dá»¯ liá»‡u'],
  ['Tr?ng thĂ¡i tr?ng', 'Tráº¡ng thĂ¡i trá»‘ng'],
  ['KhĂ´ng th? xĂ¡c th?c d? li?u batch', 'KhĂ´ng thá»ƒ xĂ¡c thá»±c dá»¯ liá»‡u batch'],
  ['Äang xĂ¡c th?c...', 'Äang xĂ¡c thá»±c...'],
  ['? D? li?u h?p l?, kh?p v?i blockchain.', 'Dá»¯ liá»‡u há»£p lá»‡, khá»›p vá»›i blockchain.'],
  ['? C?nh bĂ¡o: d? li?u hi?n t?i khĂ´ng kh?p v?i blockchain.', 'Cáº£nh bĂ¡o: dá»¯ liá»‡u hiá»‡n táº¡i khĂ´ng khá»›p vá»›i blockchain.'],
  ['Hash c?c b?:', 'Hash cá»¥c bá»™:'],
  ['T?ng quan nh? b?n l?', 'Tá»•ng quan nhĂ  bĂ¡n láº»'],
  ['Theo d?i ??n mua, ch? n?ng s?n v? giao nh?n t? d? li?u BICAP.', 'Theo dĂµi Ä‘Æ¡n mua, chá»£ nĂ´ng sáº£n vĂ  giao nháº­n tá»« dá»¯ liá»‡u BICAP.'],
  ['??n ?ang x? l?', 'ÄÆ¡n Ä‘ang xá»­ lĂ½'],
  ['T?nh t? d? li?u ??n h?ng', 'TĂ­nh tá»« dá»¯ liá»‡u Ä‘Æ¡n hĂ ng'],
  ['??n ?? nh?n', 'ÄÆ¡n Ä‘Ă£ nháº­n'],
  ['??n ?? giao ho?c ho?n t?t', 'ÄÆ¡n Ä‘Ă£ giao hoáº·c hoĂ n táº¥t'],
  ['T?ng chi ti?u', 'Tá»•ng chi tiĂªu'],
  ['Theo d? li?u ??n hi?n t?i', 'Theo dá»¯ liá»‡u Ä‘Æ¡n hiá»‡n táº¡i'],
  ['Ä‘ang ho?t Ä‘á»™ng Nh? cung c?ps', 'NhĂ  cung cáº¥p Ä‘ang hoáº¡t Ä‘á»™ng'],
  ['T? listing tr?n ch?', 'Tá»« listing trĂªn chá»£'],
  ['??n g?n ??y', 'ÄÆ¡n gáº§n Ä‘Ă¢y'],
  ['D? li?u backend', 'Dá»¯ liá»‡u backend'],
  ['C?nh b?o giao nh?n', 'Cáº£nh bĂ¡o giao nháº­n'],
  ['Ch?a c?p nh?t v? tr?', 'ChÆ°a cáº­p nháº­t vá»‹ trĂ­'],
  ['C?p nh?t backend', 'Cáº­p nháº­t backend'],
  ['M? ??n', 'MĂ£ Ä‘Æ¡n'],
  ['Nh? cung c?p', 'NhĂ  cung cáº¥p'],
  ['S?n ph?m', 'Sáº£n pháº©m'],
  ['Tr?ng th?i', 'Tráº¡ng thĂ¡i'],
  ['S? ti?n', 'Sá»‘ tiá»n'],
  ['Thao t?c', 'Thao tĂ¡c'],
  ['M? chi ti?t Ä‘Æ¡n hĂ ng', 'Má»Ÿ chi tiáº¿t Ä‘Æ¡n hĂ ng'],
  ['LÄ‚Â m m?i', 'LĂ m má»›i'],
  ['KhÄ‚Â´ng cÄ‚Â³ shipment Ă„â€˜ang gÄ‚Â¡n cho retailer.', 'KhĂ´ng cĂ³ chuyáº¿n hĂ ng Ä‘ang gĂ¡n cho nhĂ  bĂ¡n láº».'],
  ['ThÄ‚Â´ng tin th? trĂ†Â°Ă¡Â»Âng', 'ThĂ´ng tin thá»‹ trÆ°á»ng'],
  ['Tr?c ti?p', 'Trá»±c tiáº¿p'],
  ['Listing Ă„â€˜Ä‚Â£ xÄ‚Â¡c th?c', 'Listing Ä‘Ă£ xĂ¡c thá»±c'],
  ['Ch? nÄ‚Â´ng s?n chĂ†Â°a cÄ‚Â³ listing phÄ‚Â¹ h?p.', 'Chá»£ nĂ´ng sáº£n chÆ°a cĂ³ listing phĂ¹ há»£p.'],
  ['ChĂ†Â°a cÄ‚Â³ order nÄ‚Â o t? backend.', 'ChÆ°a cĂ³ Ä‘Æ¡n nĂ o tá»« backend.'],
  ['N?i dung', 'Ná»™i dung'],
  ['Äang g?i...', 'Äang gá»­i...'],
  ['G?i cho Farm', 'Gá»­i cho Farm'],
  ['ThĂ´ng bĂ¡o g?n Ä‘Ă¢y', 'ThĂ´ng bĂ¡o gáº§n Ä‘Ă¢y'],
  ['Farm, Driver vĂ  h? th?ng g?i Ä‘áº¿n retailer.', 'Farm, tĂ i xáº¿ vĂ  há»‡ thá»‘ng gá»­i Ä‘áº¿n nhĂ  bĂ¡n láº».'],
  ['Backend chÆ°a tr? v? thĂ´ng bĂ¡o cho retailer hi?n t?i.', 'Backend chÆ°a tráº£ vá» thĂ´ng bĂ¡o cho nhĂ  bĂ¡n láº» hiá»‡n táº¡i.'],
  ['Inbox thĂ´ng bĂ¡o t? Farm, Driver vĂ  h? th?ng.', 'Há»™p thÆ° thĂ´ng bĂ¡o tá»« farm, tĂ i xáº¿ vĂ  há»‡ thá»‘ng.'],
  ['T?t c? thĂ´ng bĂ¡o', 'Táº¥t cáº£ thĂ´ng bĂ¡o'],
  ['G?i bĂ¡o cĂ¡o s? c? ho?c ph?n Ă¡nh Ä‘áº¿n qu?n tr? viĂªn.', 'Gá»­i bĂ¡o cĂ¡o sá»± cá»‘ hoáº·c pháº£n Ă¡nh Ä‘áº¿n quáº£n trá»‹ viĂªn.'],
  ['T?o bĂ¡o cĂ¡o', 'Táº¡o bĂ¡o cĂ¡o'],
  ['BĂ¡o cĂ¡o Ä‘Æ°á»£c g?i Ä‘áº¿n nhĂ³m qu?n tr? viĂªn.', 'BĂ¡o cĂ¡o Ä‘Æ°á»£c gá»­i Ä‘áº¿n nhĂ³m quáº£n trá»‹ viĂªn.'],
  ['M?c Ä‘á»™', 'Má»©c Ä‘á»™'],
  ['G?i bĂ¡o cĂ¡o', 'Gá»­i bĂ¡o cĂ¡o'],
  ['Tham chi?u g?n Ä‘Ă¢y', 'Tham chiáº¿u gáº§n Ä‘Ă¢y'],
  ['CĂ¡c shipment cĂ³ th? liĂªn quan Ä‘áº¿n bĂ¡o cĂ¡o.', 'CĂ¡c chuyáº¿n hĂ ng cĂ³ thá»ƒ liĂªn quan Ä‘áº¿n bĂ¡o cĂ¡o.'],
  ['H? sÆ¡', 'Há»“ sÆ¡'],
  ['T?NG QUAN', 'Tá»”NG QUAN'],
  ['LI?N L?C', 'LIĂN Láº C'],
  ['KhĂ´ng hi?n th? l?i', 'KhĂ´ng hiá»ƒn thá»‹ láº¡i'],
  ['ch?c nÄƒng', 'chá»©c nÄƒng'],
  ['Qu?n l? blockchain / h?p Ä‘á»“ng thĂ´ng minh', 'Quáº£n lĂ½ blockchain / há»£p Ä‘á»“ng thĂ´ng minh'],
  ['Khu v?c mĂ´ ph?ng giĂ¡m sĂ¡t h?p Ä‘á»“ng thĂ´ng minh, phiĂªn b?n tri?n khai vĂ  kh? nÄƒng c?p nh?t minh b?ch truy xu?t ngu?n g?c.', 'Khu vá»±c mĂ´ phá»ng giĂ¡m sĂ¡t há»£p Ä‘á»“ng thĂ´ng minh, phiĂªn báº£n triá»ƒn khai vĂ  kháº£ nÄƒng cáº­p nháº­t minh báº¡ch truy xuáº¥t nguá»“n gá»‘c.'],
  ['h?p Ä‘á»“ng', 'há»£p Ä‘á»“ng'],
  ['M?ng:', 'Máº¡ng:'],
  ['PhiĂªn b?n:', 'PhiĂªn báº£n:'],
  ['Xem c?u h?nh', 'Xem cáº¥u hĂ¬nh'],
  ['Tri?n khai m?i', 'Triá»ƒn khai má»›i'],
  ['Ch? duy?t', 'Chá» duyá»‡t'],
  ['H? sÆ¡ nĂ´ng tr?i Ä‘ang ch? qu?n tr? viĂªn xem xĂ©t.', 'Há»“ sÆ¡ nĂ´ng tráº¡i Ä‘ang chá» quáº£n trá»‹ viĂªn xem xĂ©t.'],
  ['ChÆ°a cĂ³ tĂªn nĂ´ng tr?i', 'ChÆ°a cĂ³ tĂªn nĂ´ng tráº¡i'],
  ['ChÆ°a c?p nh?t', 'ChÆ°a cáº­p nháº­t'],
  ['Ch?ng nh?n:', 'Chá»©ng nháº­n:'],
  ['Duy?t', 'Duyá»‡t'],
  ['T? ch?i', 'Tá»« chá»‘i'],
  ['Qu?n l? chi ti?t', 'Quáº£n lĂ½ chi tiáº¿t'],
  ['ÄĂ£ duy?t', 'ÄĂ£ duyá»‡t'],
  ['CĂ¡c nĂ´ng tr?i Ä‘Ă£ h?p l? vĂ  cĂ³ th? ho?t Ä‘á»™ng trĂªn h? th?ng.', 'CĂ¡c nĂ´ng tráº¡i Ä‘Ă£ há»£p lá»‡ vĂ  cĂ³ thá»ƒ hoáº¡t Ä‘á»™ng trĂªn há»‡ thá»‘ng.'],
  ['T?ng ngÆ°á»i dĂ¹ng', 'Tá»•ng ngÆ°á»i dĂ¹ng'],
  ['Äang ho?t Ä‘á»™ng', 'Äang hoáº¡t Ä‘á»™ng'],
  ['TĂ i kho?n qu?n tr?', 'TĂ i khoáº£n quáº£n trá»‹'],
  ['NĂ´ng tr?i ch? duy?t', 'NĂ´ng tráº¡i chá» duyá»‡t'],
  ['GĂ³i d?ch v?', 'GĂ³i dá»‹ch vá»¥'],
  ['M? gĂ³i:', 'MĂ£ gĂ³i:'],
  ['Th?i h?n s? d?ng:', 'Thá»i háº¡n sá»­ dá»¥ng:'],
  ['S? mĂ¹a v? h? tr?:', 'Sá»‘ mĂ¹a vá»¥ há»— trá»£:'],
  ['S? tin Ä‘Äƒng t?i Ä‘a:', 'Sá»‘ tin Ä‘Äƒng tá»‘i Ä‘a:'],
  ['Xem chi ti?t gĂ³i', 'Xem chi tiáº¿t gĂ³i'],
  ['Qu?n l? tĂ i kho?n, vai tr? vĂ  tr?ng thĂ¡i ngÆ°á»i dĂ¹ng trĂªn h? th?ng.', 'Quáº£n lĂ½ tĂ i khoáº£n, vai trĂ² vĂ  tráº¡ng thĂ¡i ngÆ°á»i dĂ¹ng trĂªn há»‡ thá»‘ng.'],
  ['k?t qu?', 'káº¿t quáº£'],
  ['S? Ä‘iá»‡n tho?i', 'Sá»‘ Ä‘iá»‡n thoáº¡i'],
  ['Thao tĂ¡c qu?n tr? nhanh', 'Thao tĂ¡c quáº£n trá»‹ nhanh'],
  ['S? ki?n', 'Sá»± kiá»‡n'],
  ['Tin t?c', 'Tin tá»©c'],
  ['TiĂªu Ä‘á» vĂ  n?i dung khĂ´ng Ä‘Æ°á»£c Ä‘á»ƒ tr?ng', 'TiĂªu Ä‘á» vĂ  ná»™i dung khĂ´ng Ä‘Æ°á»£c Ä‘á»ƒ trá»‘ng'],
  ['C?p nh?t thĂ´ng bĂ¡o thĂ nh cĂ´ng', 'Cáº­p nháº­t thĂ´ng bĂ¡o thĂ nh cĂ´ng'],
  ['T?o thĂ´ng bĂ¡o thĂ nh cĂ´ng', 'Táº¡o thĂ´ng bĂ¡o thĂ nh cĂ´ng'],
  ['Qu?n l? thĂ´ng bĂ¡o', 'Quáº£n lĂ½ thĂ´ng bĂ¡o'],
  ['T?o, s?a, xĂ³a thĂ´ng bĂ¡o hi?n th? trĂªn trang public.', 'Táº¡o, sá»­a, xĂ³a thĂ´ng bĂ¡o hiá»ƒn thá»‹ trĂªn trang public.'],
  ['Danh m?c', 'Danh má»¥c'],
  ['ThĂ´ng bĂ¡o h? th?ng', 'ThĂ´ng bĂ¡o há»‡ thá»‘ng'],
  ['T?o, s?a, xĂ³a thĂ´ng bĂ¡o hi?n th? trĂªn public. Qu?n l? danh sĂ¡ch thĂ´ng bĂ¡o, ghim bĂ i, phĂ¢n lo?i.', 'Táº¡o, sá»­a, xĂ³a thĂ´ng bĂ¡o hiá»ƒn thá»‹ trĂªn public. Quáº£n lĂ½ danh sĂ¡ch thĂ´ng bĂ¡o, ghim bĂ i, phĂ¢n loáº¡i.'],
  ['BĂ i vi?t giĂ¡o d?c', 'BĂ i viáº¿t giĂ¡o dá»¥c'],
  ['T?o n?i dung giĂ¡o d?c, hÆ°á»›ng d?n, tin t?c nĂ´ng nghi?p cho guest/public.', 'Táº¡o ná»™i dung giĂ¡o dá»¥c, hÆ°á»›ng dáº«n, tin tá»©c nĂ´ng nghiá»‡p cho khĂ¡ch/public.'],
  ['Giao di?n website', 'Giao diá»‡n website'],
  ['Qu?n l? tĂ i nguyĂªn hi?n th?, hero, preview vĂ  c?u h?nh giao di?n public.', 'Quáº£n lĂ½ tĂ i nguyĂªn hiá»ƒn thá»‹, hero, preview vĂ  cáº¥u hĂ¬nh giao diá»‡n public.'],
  ['Duy?t listing lĂªn sĂ n vĂ  theo d?i bĂ¡o cĂ¡o t? cĂ¡c vai tr? v?n hĂ nh.', 'Duyá»‡t listing lĂªn sĂ n vĂ  theo dĂµi bĂ¡o cĂ¡o tá»« cĂ¡c vai trĂ² váº­n hĂ nh.'],
  ['ThĂ´ng bĂ¡o & n?i dung', 'ThĂ´ng bĂ¡o vĂ  ná»™i dung'],
  ['Äiá»u ph?i n?i dung h? th?ng, public website vĂ  lu?ng truy?n thĂ´ng v?n hĂ nh.', 'Äiá»u phá»‘i ná»™i dung há»‡ thá»‘ng, website public vĂ  luá»“ng truyá»n thĂ´ng váº­n hĂ nh.'],
  ['M? ch?c nÄƒng', 'Má»Ÿ chá»©c nÄƒng'],
  ['Module Ä‘Ă£ s?n sĂ ng Ä‘á»ƒ m? r?ng CRUD.', 'Module Ä‘Ă£ sáºµn sĂ ng Ä‘á»ƒ má»Ÿ rá»™ng CRUD.'],
  ['ÄĂ£ xĂ¡c th?c', 'ÄĂ£ xĂ¡c thá»±c'],
  ['Ch? xĂ¡c th?c', 'Chá» xĂ¡c thá»±c'],
  ['ChÆ°a c?p nh?t nĂ´ng tr?i', 'ChÆ°a cáº­p nháº­t nĂ´ng tráº¡i'],
  ['ChÆ°a c?p nh?t xu?t x?', 'ChÆ°a cáº­p nháº­t xuáº¥t xá»©'],
  ['LiĂªn h?', 'LiĂªn há»‡'],
  ['Äang ch?', 'Äang chá»'],
  ['ChÆ°a cĂ³ nh?t k? s?n xu?t nĂ o Ä‘Æ°á»£c cĂ´ng b? cho lĂ´ hĂ ng nĂ y.', 'ChÆ°a cĂ³ nháº­t kĂ½ sáº£n xuáº¥t nĂ o Ä‘Æ°á»£c cĂ´ng bá»‘ cho lĂ´ hĂ ng nĂ y.'],
  ['Gieo tr?ng', 'Gieo trá»“ng'],
  ['LĂ´ gi?ng Ä‘Ă£ Ä‘Æ°á»£c ghi nh?n. Äáº¥t Ä‘Æ°á»£c chu?n b? b?ng phĂ¢n h?u cÆ¡.', 'LĂ´ giá»‘ng Ä‘Ă£ Ä‘Æ°á»£c ghi nháº­n. Äáº¥t Ä‘Æ°á»£c chuáº©n bá»‹ báº±ng phĂ¢n há»¯u cÆ¡.'],
  ['ChÄƒm sĂ³c cĂ¢y tr?ng', 'ChÄƒm sĂ³c cĂ¢y trá»“ng'],
  ['Nh?t k? tÆ°á»›i tiĂªu vĂ  ki?m soĂ¡t sĂ¢u b?nh Ä‘Ă£ Ä‘Æ°á»£c Ä‘á»“ng b?.', 'Nháº­t kĂ½ tÆ°á»›i tiĂªu vĂ  kiá»ƒm soĂ¡t sĂ¢u bá»‡nh Ä‘Ă£ Ä‘Æ°á»£c Ä‘á»“ng bá»™.'],
  ['Thu ho?ch', 'Thu hoáº¡ch'],
  ['S?n lÆ°á»£ng thu ho?ch Ä‘Æ°á»£c ki?m tra vĂ  liĂªn k?t v?i lĂ´ s?n ph?m.', 'Sáº£n lÆ°á»£ng thu hoáº¡ch Ä‘Æ°á»£c kiá»ƒm tra vĂ  liĂªn káº¿t vá»›i lĂ´ sáº£n pháº©m.'],
  ['Äang ch? chuy?n Ä‘áº¿n khu lÆ°u tr? ki?m soĂ¡t nhi?t Ä‘á»™.', 'Äang chá» chuyá»ƒn Ä‘áº¿n khu lÆ°u trá»¯ kiá»ƒm soĂ¡t nhiá»‡t Ä‘á»™.'],
  ['BÆ°á»›c truy xu?t', 'BÆ°á»›c truy xuáº¥t'],
  ['Ho?t Ä‘á»™ng s?n xu?t Ä‘Ă£ Ä‘Æ°á»£c ghi nh?n trong BICAP.', 'Hoáº¡t Ä‘á»™ng sáº£n xuáº¥t Ä‘Ă£ Ä‘Æ°á»£c ghi nháº­n trong BICAP.'],
  ['Marketplace t?m th?i khĂ´ng kh? d?ng', 'Marketplace táº¡m thá»i khĂ´ng kháº£ dá»¥ng'],
  ['Qu?n tr? n?n t?ng', 'Quáº£n trá»‹ ná»n táº£ng'],
  ['KhĂ´ng gian NĂ´ng tr?i', 'KhĂ´ng gian NĂ´ng tráº¡i'],
  ['T?ng quan V?n chuy?n', 'Tá»•ng quan Váº­n chuyá»ƒn'],
  ['Truy xu?t ngu?n g?c nĂ´ng s?n', 'Truy xuáº¥t nguá»“n gá»‘c nĂ´ng sáº£n'],
  ['KhĂ´ng t?i Ä‘Æ°á»£c danh sĂ¡ch chuy?n hĂ ng.', 'KhĂ´ng táº£i Ä‘Æ°á»£c danh sĂ¡ch chuyáº¿n hĂ ng.'],
  ['ÄĂ£ quĂ©t m?', 'ÄĂ£ quĂ©t mĂ£'],
  ['KhĂ´ng th? m? camera', 'KhĂ´ng thá»ƒ má»Ÿ camera'],
  ['C?p nh?t proof', 'Cáº­p nháº­t proof'],
  ['KhĂ´ng t?i Ä‘Æ°á»£c order workflow.', 'KhĂ´ng táº£i Ä‘Æ°á»£c luá»“ng Ä‘Æ¡n hĂ ng.'],
  ['ÄĂ£ thanh toĂ¡n Ä‘áº·t c?c.', 'ÄĂ£ thanh toĂ¡n Ä‘áº·t cá»c.'],
  ['KhĂ´ng thanh toĂ¡n Ä‘Æ°á»£c Ä‘áº·t c?c.', 'KhĂ´ng thanh toĂ¡n Ä‘Æ°á»£c Ä‘áº·t cá»c.'],
  ['ÄĂ£ h?y Ä‘Æ¡n hĂ ng.', 'ÄĂ£ há»§y Ä‘Æ¡n hĂ ng.'],
  ['KhĂ´ng h?y Ä‘Æ°á»£c Ä‘Æ¡n hĂ ng.', 'KhĂ´ng há»§y Ä‘Æ°á»£c Ä‘Æ¡n hĂ ng.'],
  ['ÄĂ£ xĂ¡c nh?n nh?n hĂ ng hoĂ n t?t.', 'ÄĂ£ xĂ¡c nháº­n nháº­n hĂ ng hoĂ n táº¥t.'],
  ['KhĂ´ng xĂ¡c nh?n Ä‘Æ°á»£c giao hĂ ng.', 'KhĂ´ng xĂ¡c nháº­n Ä‘Æ°á»£c giao hĂ ng.'],
  ['KhĂ´ng Ä‘Ă¡nh d?u notification Ä‘Æ°á»£c.', 'KhĂ´ng Ä‘Ă¡nh dáº¥u thĂ´ng bĂ¡o Ä‘Æ°á»£c.'],
  ['H? sÆ¡ Ä‘Ă£ Ä‘Æ°á»£c c?p nh?t t? backend.', 'Há»“ sÆ¡ Ä‘Ă£ Ä‘Æ°á»£c cáº­p nháº­t tá»« backend.'],
  ['KhĂ´ng th? c?p nh?t h? sÆ¡.', 'KhĂ´ng thá»ƒ cáº­p nháº­t há»“ sÆ¡.'],
  ['M?t kh?u xĂ¡c nh?n khĂ´ng kh?p.', 'Máº­t kháº©u xĂ¡c nháº­n khĂ´ng khá»›p.'],
  ['M?t kh?u Ä‘Ă£ Ä‘Æ°á»£c c?p nh?t.', 'Máº­t kháº©u Ä‘Ă£ Ä‘Æ°á»£c cáº­p nháº­t.'],
  ['KhĂ´ng th? Ä‘á»•i m?t kh?u.', 'KhĂ´ng thá»ƒ Ä‘á»•i máº­t kháº©u.'],
  ['Ch? nĂ´ng s?n', 'Chá»£ nĂ´ng sáº£n'],
  ['s?n ph?m', 'sáº£n pháº©m'],
  ['b? l?c', 'bá»™ lá»c'],
  ['T?m theo tĂªn s?n ph?m, nĂ´ng tr?i...', 'TĂ¬m theo tĂªn sáº£n pháº©m, nĂ´ng tráº¡i...'],
  ['T?t c? khu v?c', 'Táº¥t cáº£ khu vá»±c'],
  ['Äang t?i s?n ph?m...', 'Äang táº£i sáº£n pháº©m...'],
  ['KhĂ´ng t?m th?y s?n ph?m', 'KhĂ´ng tĂ¬m tháº¥y sáº£n pháº©m'],
  ['Th? thay Ä‘á»•i t? khĂ³a ho?c b? l?c.', 'Thá»­ thay Ä‘á»•i tá»« khĂ³a hoáº·c bá»™ lá»c.'],
  ['CĂ³ truy xu?t', 'CĂ³ truy xuáº¥t'],
  ['S?n ph?m', 'Sáº£n pháº©m'],
  ['C?n l?i', 'CĂ²n láº¡i'],
  ['Ti?p ?', 'Tiáº¿p'],
  ['Chi ti?t s?n ph?m', 'Chi tiáº¿t sáº£n pháº©m'],
  ['Click vĂ o 1 s?n ph?m Ä‘á»ƒ xem chi ti?t.', 'Chá»n 1 sáº£n pháº©m Ä‘á»ƒ xem chi tiáº¿t.'],
  ['KhĂ´ng cĂ³ mĂ´ t?.', 'KhĂ´ng cĂ³ mĂ´ táº£.'],
  ['NĂ´ng tr?i', 'NĂ´ng tráº¡i'],
  ['Khu v?c', 'Khu vá»±c'],
  ['ÄÆ¡n v?', 'ÄÆ¡n vá»‹'],
  ['Ch?ng nh?n', 'Chá»©ng nháº­n'],
  ['Truy xu?t', 'Truy xuáº¥t'],
  ['? CĂ³ m? QR', 'CĂ³ mĂ£ QR'],
  ['Truy xu?t ngu?n g?c', 'Truy xuáº¥t nguá»“n gá»‘c'],
  ['Há»“ sÆ¡ retailer', 'Há»“ sÆ¡ nhĂ  bĂ¡n láº»'],
  ['Qu?n l? thĂ´ng tin doanh nghi?p vĂ  gi?y phĂ©p bĂ¡n l?.', 'Quáº£n lĂ½ thĂ´ng tin doanh nghiá»‡p vĂ  giáº¥y phĂ©p bĂ¡n láº».'],
  ['ChÆ°a Ä‘á»§ Ä‘iá»u ki?n Ä‘áº·t hĂ ng', 'ChÆ°a Ä‘á»§ Ä‘iá»u kiá»‡n Ä‘áº·t hĂ ng'],
  ['ChÆ°a c?u h?nh h? sÆ¡ retailer', 'ChÆ°a cáº¥u hĂ¬nh há»“ sÆ¡ nhĂ  bĂ¡n láº»'],
  ['Ch?a c? email', 'ChÆ°a cĂ³ email'],
  ['ChÆ°a cĂ³ m? retailer', 'ChÆ°a cĂ³ mĂ£ nhĂ  bĂ¡n láº»'],
  ['H? sÆ¡ nghi?p v?', 'Há»“ sÆ¡ nghiá»‡p vá»¥'],
  ['ÄĂ£ t?o', 'ÄĂ£ táº¡o'],
  ['ChÆ°a t?o', 'ChÆ°a táº¡o'],
  ['ÄÆ¡n Ä‘ang x? l?', 'ÄÆ¡n Ä‘ang xá»­ lĂ½'],
  ['Shipment Ä‘Ă£ nh?n', 'Shipment Ä‘Ă£ nháº­n'],
  ['H? sÆ¡ phĂ¡p l? retailer', 'Há»“ sÆ¡ phĂ¡p lĂ½ nhĂ  bĂ¡n láº»'],
  ['ThĂ´ng tin nĂ y quy?t Ä‘á»‹nh quy?n Ä‘áº·t hĂ ng vĂ  g?n order v?i retailer.', 'ThĂ´ng tin nĂ y quyáº¿t Ä‘á»‹nh quyá»n Ä‘áº·t hĂ ng vĂ  gáº¯n Ä‘Æ¡n vá»›i nhĂ  bĂ¡n láº».'],
  ['M? nh? b?n l?', 'MĂ£ nhĂ  bĂ¡n láº»'],
  ['S? gi?y ph?p kinh doanh', 'Sá»‘ giáº¥y phĂ©p kinh doanh'],
  ['TĂªn doanh nghi?p / c?a hĂ ng', 'TĂªn doanh nghiá»‡p / cá»­a hĂ ng'],
  ['Tr?ng thĂ¡i nghi?p v?', 'Tráº¡ng thĂ¡i nghiá»‡p vá»¥'],
  ['ACTIVE sau khi t?o', 'ACTIVE sau khi táº¡o'],
  ['??a ch? c?a h?ng', 'Äá»‹a chá»‰ cá»­a hĂ ng'],
  ['ChÆ°a ch?n t?p gi?y phĂ©p.', 'ChÆ°a chá»n tá»‡p giáº¥y phĂ©p.'],
  ['Ch?n t?p', 'Chá»n tá»‡p'],
  ['LÆ°u h? sÆ¡', 'LÆ°u há»“ sÆ¡'],
  ['Äiá»u ki?n nghi?p v?', 'Äiá»u kiá»‡n nghiá»‡p vá»¥'],
  ['Tr?ng th?i', 'Tráº¡ng thĂ¡i'],
  ['Th?ng tin ph?p l?', 'ThĂ´ng tin phĂ¡p lĂ½'],
  ['Thi?u thĂ´ng tin b?t bu?c', 'Thiáº¿u thĂ´ng tin báº¯t buá»™c'],
  ['T?p gi?y ph?p', 'Tá»‡p giáº¥y phĂ©p'],
  ['Quy?n ??t h?ng', 'Quyá»n Ä‘áº·t hĂ ng'],
  ['Cho phĂ©p t?o order', 'Cho phĂ©p táº¡o Ä‘Æ¡n'],
  ['B? ch?n b?i backend', 'Bá»‹ cháº·n bá»Ÿi backend'],
  ['TĂ i kho?n ngÆ°á»i Ä‘áº¡i di?n', 'TĂ i khoáº£n ngÆ°á»i Ä‘áº¡i diá»‡n'],
  ['ThĂ´ng tin Ä‘Äƒng nh?p vĂ  liĂªn h? cĂ¡ nhĂ¢n c?a ngÆ°á»i mua.', 'ThĂ´ng tin Ä‘Äƒng nháº­p vĂ  liĂªn há»‡ cĂ¡ nhĂ¢n cá»§a ngÆ°á»i mua.'],
  ['H? tĂªn', 'Há» tĂªn'],
  ['Email Ä‘Äƒng nh?p', 'Email Ä‘Äƒng nháº­p'],
  ['S? Ä‘iá»‡n tho?i', 'Sá»‘ Ä‘iá»‡n thoáº¡i'],
  ['Vai tr?', 'Vai trĂ²'],
  ['LÆ°u tĂ i kho?n', 'LÆ°u tĂ i khoáº£n'],
  ['B?o m?t', 'Báº£o máº­t'],
  ['Äá»•i m?t kh?u tĂ i kho?n retailer.', 'Äá»•i máº­t kháº©u tĂ i khoáº£n nhĂ  bĂ¡n láº».'],
  ['M?t kh?u hi?n t?i', 'Máº­t kháº©u hiá»‡n táº¡i'],
  ['M?t kh?u m?i', 'Máº­t kháº©u má»›i'],
  ['XĂ¡c nh?n m?t kh?u', 'XĂ¡c nháº­n máº­t kháº©u'],
  ['Äá»•i m?t kh?u', 'Äá»•i máº­t kháº©u'],
])

const TOKEN_REPAIRS = [
  [/mĂ¹a v\?/g, 'mĂ¹a vá»¥'],
  [/MĂ¹a v\?/g, 'MĂ¹a vá»¥'],
  [/MĂ™A V\?/g, 'MĂ™A Vá»¤'],
  [/S\?N XUáº¤T/g, 'Sáº¢N XUáº¤T'],
  [/S\?N PHáº¨M/g, 'Sáº¢N PHáº¨M'],
  [/S\? LÆ¯á»¢NG/g, 'Sá» LÆ¯á»¢NG'],
  [/B\?T Äáº¦U/g, 'Báº®T Äáº¦U'],
  [/cáº§n lá»—i/g, 'cĂ²n láº¡i'],
  [/cáºµn lá»—i/g, 'cĂ²n láº¡i'],
  [/quy tr\?nh/g, 'quy trĂ¬nh'],
  [/Quy tr\?nh/g, 'Quy trĂ¬nh'],
  [/s\? mĂ¹a/g, 'sá»‘ mĂ¹a'],
  [/S\? mĂ¹a/g, 'Sá»‘ mĂ¹a'],
  [/s\? lĂ´/g, 'sá»‘ lĂ´'],
  [/S\? lĂ´/g, 'Sá»‘ lĂ´'],
  [/s\?n sĂ ng/g, 'sáºµn sĂ ng'],
  [/S\?n sĂ ng/g, 'Sáºµn sĂ ng'],
  [/thu ho\?ch/g, 'thu hoáº¡ch'],
  [/Thu ho\?ch/g, 'Thu hoáº¡ch'],
  [/bĂ¡n h\?t/g, 'bĂ¡n háº¿t'],
  [/BĂ¡n h\?t/g, 'BĂ¡n háº¿t'],
  [/cĂ²n l\?i/g, 'cĂ²n láº¡i'],
  [/CĂ²n l\?i/g, 'CĂ²n láº¡i'],
  [/kh\? d\?ng/g, 'kháº£ dá»¥ng'],
  [/Kh\? d\?ng/g, 'Kháº£ dá»¥ng'],
  [/M\? mĂ¹a/g, 'MĂ£ mĂ¹a'],
  [/m\? mĂ¹a/g, 'mĂ£ mĂ¹a'],
  [/M\? lĂ´/g, 'MĂ£ lĂ´'],
  [/m\? lĂ´/g, 'mĂ£ lĂ´'],
  [/M\? batch/g, 'MĂ£ batch'],
  [/M\? BATCH/g, 'MĂƒ BATCH'],
  [/T\?o mĂ¹a/g, 'Táº¡o mĂ¹a'],
  [/t\?o mĂ¹a/g, 'táº¡o mĂ¹a'],
  [/T\?o lĂ´/g, 'Táº¡o lĂ´'],
  [/t\?o lĂ´/g, 'táº¡o lĂ´'],
  [/Ch\?n mĂ¹a/g, 'Chá»n mĂ¹a'],
  [/ch\?n mĂ¹a/g, 'chá»n mĂ¹a'],
  [/duy nh\?t/g, 'duy nháº¥t'],
  [/Duy nh\?t/g, 'Duy nháº¥t'],
  [/Ä‘á» xu\?t/g, 'Ä‘á» xuáº¥t'],
  [/Äá» xu\?t/g, 'Äá» xuáº¥t'],
  [/cĂ³ th\? Ä‘á»•i/g, 'cĂ³ thá»ƒ Ä‘á»•i'],
  [/CĂ³ th\? Ä‘á»•i/g, 'CĂ³ thá»ƒ Ä‘á»•i'],
  [/xu\?t/g, 'xuáº¥t'],
  [/Xu\?t/g, 'Xuáº¥t'],
  [/TR\?NG THĂI/g, 'TRáº NG THĂI'],
  [/B\?T Äáº¦U/g, 'Báº®T Äáº¦U'],
  [/D\? KI\?N/g, 'Dá»° KIáº¾N'],
  [/T\?ng/g, 'Tá»•ng'],
  [/\?\?n/g, 'ÄÆ¡n'],
  [/\?ang/g, 'Ä‘ang'],
  [/\?\?/g, 'Ä‘Ă£'],
  [/\?i/g, 'Ăµi'],
  [/d\? li\?u/g, 'dá»¯ liá»‡u'],
  [/nh\? b\?n l\?/g, 'nhĂ  bĂ¡n láº»'],
  [/ch\? n\?ng s\?n/g, 'chá»£ nĂ´ng sáº£n'],
  [/giao nh\?n/g, 'giao nháº­n'],
  [/h\? th\?ng/g, 'há»‡ thá»‘ng'],
  [/t\? backend/g, 'tá»« backend'],
  [/hi\?n t\?i/g, 'hiá»‡n táº¡i'],
  [/c\?p nh\?t/g, 'cáº­p nháº­t'],
  [/v\? tr\?/g, 'vá»‹ trĂ­'],
  [/c\?nh b\?o/g, 'cáº£nh bĂ¡o'],
  [/g\?n \?\?y/g, 'gáº§n Ä‘Ă¢y'],
  [/tr\? v\?/g, 'tráº£ vá»'],
  [/qu\?n tr\?/g, 'quáº£n trá»‹'],
  [/s\? c\?/g, 'sá»± cá»‘'],
  [/ph\?n Ă¡nh/g, 'pháº£n Ă¡nh'],
  [/N\?i dung/g, 'Ná»™i dung'],
  [/G\?i/g, 'Gá»­i'],
  [/t\?i/g, 'táº£i'],
  [/T\?i/g, 'Táº£i'],
  [/d\?ch v\?/g, 'dá»‹ch vá»¥'],
  [/D\?ch v\?/g, 'Dá»‹ch vá»¥'],
  [/qu\?n l\?/g, 'quáº£n lĂ½'],
  [/Qu\?n l\?/g, 'Quáº£n lĂ½'],
  [/tĂ i kho\?n/g, 'tĂ i khoáº£n'],
  [/TĂ i kho\?n/g, 'TĂ i khoáº£n'],
  [/vai tr\?/g, 'vai trĂ²'],
  [/Vai tr\?/g, 'Vai trĂ²'],
  [/tr\?ng thĂ¡i/g, 'tráº¡ng thĂ¡i'],
  [/Tr\?ng thĂ¡i/g, 'Tráº¡ng thĂ¡i'],
  [/ho\?t Ä‘á»™ng/g, 'hoáº¡t Ä‘á»™ng'],
  [/Ho\?t Ä‘á»™ng/g, 'Hoáº¡t Ä‘á»™ng'],
  [/duy\?t/g, 'duyá»‡t'],
  [/Duy\?t/g, 'Duyá»‡t'],
  [/t\? ch\?i/g, 'tá»« chá»‘i'],
  [/T\? ch\?i/g, 'Tá»« chá»‘i'],
  [/h\? sÆ¡/g, 'há»“ sÆ¡'],
  [/H\? sÆ¡/g, 'Há»“ sÆ¡'],
  [/nĂ´ng tr\?i/g, 'nĂ´ng tráº¡i'],
  [/NĂ´ng tr\?i/g, 'NĂ´ng tráº¡i'],
  [/s\?n ph\?m/g, 'sáº£n pháº©m'],
  [/S\?n ph\?m/g, 'Sáº£n pháº©m'],
  [/s\?n xu\?t/g, 'sáº£n xuáº¥t'],
  [/S\?n xu\?t/g, 'Sáº£n xuáº¥t'],
  [/truy xu\?t/g, 'truy xuáº¥t'],
  [/Truy xu\?t/g, 'Truy xuáº¥t'],
  [/ngu\?n g\?c/g, 'nguá»“n gá»‘c'],
  [/Ngu\?n g\?c/g, 'Nguá»“n gá»‘c'],
  [/n\?i dung/g, 'ná»™i dung'],
  [/N\?i dung/g, 'Ná»™i dung'],
  [/hi\?n th\?/g, 'hiá»ƒn thá»‹'],
  [/Hi\?n th\?/g, 'Hiá»ƒn thá»‹'],
  [/c\?u h\?nh/g, 'cáº¥u hĂ¬nh'],
  [/C\?u h\?nh/g, 'Cáº¥u hĂ¬nh'],
  [/m\?i/g, 'má»›i'],
  [/M\?i/g, 'Má»›i'],
  [/s\?a/g, 'sá»­a'],
  [/S\?a/g, 'Sá»­a'],
  [/x\?a/g, 'xĂ³a'],
  [/X\?a/g, 'XĂ³a'],
  [/n\?u/g, 'náº¿u'],
  [/N\?u/g, 'Náº¿u'],
  [/c\?n/g, 'cáº§n'],
  [/C\?n/g, 'Cáº§n'],
  [/c\? th\?/g, 'cĂ³ thá»ƒ'],
  [/C\? th\?/g, 'CĂ³ thá»ƒ'],
  [/h\?p l\?/g, 'há»£p lá»‡'],
  [/H\?p l\?/g, 'Há»£p lá»‡'],
  [/k\?t n\?i/g, 'káº¿t ná»‘i'],
  [/K\?t n\?i/g, 'Káº¿t ná»‘i'],
  [/k\?t qu\?/g, 'káº¿t quáº£'],
  [/K\?t qu\?/g, 'Káº¿t quáº£'],
  [/th\?i gian/g, 'thá»i gian'],
  [/Th\?i gian/g, 'Thá»i gian'],
  [/ch\? duy\?t/g, 'chá» duyá»‡t'],
  [/Ch\? duy\?t/g, 'Chá» duyá»‡t'],
  [/ch\? xĂ¡c th\?c/g, 'chá» xĂ¡c thá»±c'],
  [/Ch\? xĂ¡c th\?c/g, 'Chá» xĂ¡c thá»±c'],
  [/gi\?y phĂ©p/g, 'giáº¥y phĂ©p'],
  [/Gi\?y phĂ©p/g, 'Giáº¥y phĂ©p'],
  [/ch\?ng nh\?n/g, 'chá»©ng nháº­n'],
  [/Ch\?ng nh\?n/g, 'Chá»©ng nháº­n'],
  [/s\? Ä‘i\?n tho\?i/g, 'sá»‘ Ä‘iá»‡n thoáº¡i'],
  [/S\? Ä‘i\?n tho\?i/g, 'Sá»‘ Ä‘iá»‡n thoáº¡i'],
  [/Ä‘\?t c\?c/g, 'Ä‘áº·t cá»c'],
  [/Ä\?t c\?c/g, 'Äáº·t cá»c'],
  [/h\?y/g, 'há»§y'],
  [/H\?y/g, 'Há»§y'],
  [/xĂ¡c nh\?n/g, 'xĂ¡c nháº­n'],
  [/XĂ¡c nh\?n/g, 'XĂ¡c nháº­n'],
  [/nh\?n hĂ ng/g, 'nháº­n hĂ ng'],
  [/Nh\?n hĂ ng/g, 'Nháº­n hĂ ng'],
  [/chuy\?n hĂ ng/g, 'chuyáº¿n hĂ ng'],
  [/Chuy\?n hĂ ng/g, 'Chuyáº¿n hĂ ng'],
  [/thĂ´ng bĂ¡o/g, 'thĂ´ng bĂ¡o'],
  [/ThĂ´ng bĂ¡o/g, 'ThĂ´ng bĂ¡o'],
  [/TIN T\?C/g, 'TIN Tá»¨C'],
  [/S\? KI\?N/g, 'Sá»° KIá»†N'],
  [/H\? TH\?NG/g, 'Há»† THá»NG'],
  [/HÆ¯á»NG D\?N/g, 'HÆ¯á»NG DáºªN'],
  [/BĂ€I VI\?T/g, 'BĂ€I VIáº¾T'],
]

const FARM_PHASE_REPAIRS = [
  [/mĂ¹a v\?/g, 'mĂ¹a vá»¥'],
  [/MĂ¹a v\?/g, 'MĂ¹a vá»¥'],
  [/MĂ™A V\?/g, 'MĂ™A Vá»¤'],
  [/quy tr\?nh/g, 'quy trĂ¬nh'],
  [/Quy tr\?nh/g, 'Quy trĂ¬nh'],
  [/chi ti\?t/g, 'chi tiáº¿t'],
  [/Chi ti\?t/g, 'Chi tiáº¿t'],
  [/Tá»•ng s\?/g, 'Tá»•ng sá»‘'],
  [/s\? lĂ´/g, 'sá»‘ lĂ´'],
  [/S\? lĂ´/g, 'Sá»‘ lĂ´'],
  [/s\?n sĂ ng/g, 'sáºµn sĂ ng'],
  [/S\?n sĂ ng/g, 'Sáºµn sĂ ng'],
  [/Ä‘ang tr\?ng/g, 'Ä‘ang trá»“ng'],
  [/Äang tr\?ng/g, 'Äang trá»“ng'],
  [/thu ho\?ch/g, 'thu hoáº¡ch'],
  [/Thu ho\?ch/g, 'Thu hoáº¡ch'],
  [/Ä‘Ă£ bĂ¡n h\?t/g, 'Ä‘Ă£ bĂ¡n háº¿t'],
  [/ÄĂ£ bĂ¡n h\?t/g, 'ÄĂ£ bĂ¡n háº¿t'],
  [/cĂ²n l\?i/g, 'cĂ²n láº¡i'],
  [/CĂ²n l\?i/g, 'CĂ²n láº¡i'],
  [/kh\? d\?ng/g, 'kháº£ dá»¥ng'],
  [/Kh\? d\?ng/g, 'Kháº£ dá»¥ng'],
  [/d\?ng/g, 'dĂ²ng'],
  [/D\?ng/g, 'DĂ²ng'],
  [/M\? /g, 'MĂ£ '],
  [/m\? /g, 'mĂ£ '],
  [/M\?/g, 'MĂ£'],
  [/m\?/g, 'mĂ£'],
  [/B\?T Äáº¦U/g, 'Báº®T Äáº¦U'],
  [/D\? KI\?N/g, 'Dá»° KIáº¾N'],
  [/d\? ki\?n/g, 'dá»± kiáº¿n'],
  [/D\? ki\?n/g, 'Dá»± kiáº¿n'],
  [/duy nh\?t/g, 'duy nháº¥t'],
  [/Duy nh\?t/g, 'Duy nháº¥t'],
  [/Ä‘á» xu\?t/g, 'Ä‘á» xuáº¥t'],
  [/Äá» xu\?t/g, 'Äá» xuáº¥t'],
  [/xu\?t/g, 'xuáº¥t'],
  [/Xu\?t/g, 'Xuáº¥t'],
  [/cĂ³ th\?/g, 'cĂ³ thá»ƒ'],
  [/CĂ³ th\?/g, 'CĂ³ thá»ƒ'],
  [/Ch\?n/g, 'Chá»n'],
  [/ch\?n/g, 'chá»n'],
  [/T\?o/g, 'Táº¡o'],
  [/t\?o/g, 'táº¡o'],
  [/H\?n/g, 'Háº¡n'],
  [/h\?n/g, 'háº¡n'],
  [/s\? d\?ng/g, 'sá»­ dá»¥ng'],
  [/S\? d\?ng/g, 'Sá»­ dá»¥ng'],
  [/l\?i/g, 'láº¡i'],
  [/L\?i/g, 'Láº¡i'],
  [/T\?m/g, 'TĂ¬m'],
  [/t\?m/g, 'tĂ¬m'],
  [/nghi\?p/g, 'nghiá»‡p'],
  [/Nghi\?p/g, 'Nghiá»‡p'],
  [/doanh nghi\?p/g, 'doanh nghiá»‡p'],
  [/Doanh nghi\?p/g, 'Doanh nghiá»‡p'],
  [/ph\?p/g, 'phĂ©p'],
  [/Ph\?p/g, 'PhĂ©p'],
  [/gi\?y/g, 'giáº¥y'],
  [/Gi\?y/g, 'Giáº¥y'],
  [/khu v\?c/g, 'khu vá»±c'],
  [/Khu v\?c/g, 'Khu vá»±c'],
  [/nĂ´ng tr\?i/g, 'nĂ´ng tráº¡i'],
  [/NĂ´ng tr\?i/g, 'NĂ´ng tráº¡i'],
  [/th\? trĂ†Â°Ă¡Â»Âng/g, 'thá»‹ trÆ°á»ng'],
  [/Th\? trĂ†Â°Ă¡Â»Âng/g, 'Thá»‹ trÆ°á»ng'],
  [/c\?u h\?nh/g, 'cáº¥u hĂ¬nh'],
  [/C\?u h\?nh/g, 'Cáº¥u hĂ¬nh'],
  [/c\?p/g, 'cấp'],
  [/C\?p/g, 'Cấp'],
  [/s\? d[ùu]ng/g, 'sử dụng'],
  [/n\?n t[aá]ng/g, 'nền tảng'],
  [/n\?n t\?ng/g, 'nền tảng'],
  [/Qu\?n tr\?/g, 'Quản trị'],
  [/\bb\?n\b/g, 'bạn'],
  [/c\?ng/g, 'cổng'],
  [/Tr\?ng th[aá]i/g, 'Trạng thái'],
  [/L\?ch s\?/g, 'Lịch sử'],
  [/ch\? thanh/g, 'chờ thanh'],
  [/Hi\?u l\?c/g, 'Hiệu lực'],
  [/Ghi chú \?/g, 'Ghi chú'],
  [/Lưu \?:/g, 'Lưu ý:'],
  [/chuy\?n sang/g, 'chuyển sang'],
  [/duy\?t l\?i/g, 'duyệt lại'],  [/t\?p/g, 'tệp'],
  [/c\?p/g, 'cấp'],
  [/C\?p/g, 'Cấp'],
  [/s\? d[ùu]ng/g, 'sử dụng'],
  [/n\?n t[aá]ng/g, 'nền tảng'],
  [/n\?n t\?ng/g, 'nền tảng'],
  [/Qu\?n tr\?/g, 'Quản trị'],
  [/\bb\?n\b/g, 'bạn'],
  [/c\?ng/g, 'cổng'],
  [/Tr\?ng th[aá]i/g, 'Trạng thái'],
  [/L\?ch s\?/g, 'Lịch sử'],
  [/ch\? thanh/g, 'chờ thanh'],
  [/Hi\?u l\?c/g, 'Hiệu lực'],
  [/Ghi chú \?/g, 'Ghi chú'],
  [/Lưu \?:/g, 'Lưu ý:'],
  [/chuy\?n sang/g, 'chuyển sang'],
  [/duy\?t l\?i/g, 'duyệt lại'],  [/t\?p/g, 'tệp'],
  [/c\?a hÄ‚Â ng/g, 'cá»­a hĂ ng'],
  [/C\?a hÄ‚Â ng/g, 'Cá»­a hĂ ng'],
  [/v\?/g, 'vá»¥'],
  [/V\?/g, 'Vá»¥'],
]

const FINAL_TEXT_REPAIRS = [
  ['nĂ´ng trá»—i', 'nĂ´ng tráº¡i'],
  ['NĂ´ng trá»—i', 'NĂ´ng tráº¡i'],
  ['Há»“ sÆ¡ phĂ¡p l? retailer', 'Há»“ sÆ¡ phĂ¡p lĂ½ nhĂ  bĂ¡n láº»'],
  ['Há»“ sÆ¡ phĂ¡p l?', 'Há»“ sÆ¡ phĂ¡p lĂ½'],
  ['phĂ¡p l?', 'phĂ¡p lĂ½'],
  ['ThĂ´ng tin th? trÆ°á»ng', 'ThĂ´ng tin thá»‹ trÆ°á»ng'],
  ['th? trÆ°á»ng', 'thá»‹ trÆ°á»ng'],
  ['TĂ¬m theo tĂªn sáº£n pháº©m, nĂ´ng trá»—i...', 'TĂ¬m theo tĂªn sáº£n pháº©m, nĂ´ng tráº¡i...'],
  ['ThĂ´ng tin thá»‹ trÆ°á»ng', 'ThĂ´ng tin thá»‹ trÆ°á»ng'],
]

export function repairText(value) {
  if (!value || typeof value !== 'string') return value
  let next = value
  if (/[ĂƒĂ‚Ă„]/.test(next)) {
    try {
      const decoded = new TextDecoder('utf-8', { fatal: true }).decode(Uint8Array.from(next, (char) => char.charCodeAt(0) & 0xff))
      if (decoded && decoded !== next) next = decoded
    } catch {
      // Keep explicit repairs below for mixed/partially damaged strings.
    }
  }
  for (const [bad, good] of EXACT_REPAIRS) next = next.split(bad).join(good)
  for (const [pattern, good] of TOKEN_REPAIRS) next = next.replace(pattern, good)
  for (const [pattern, good] of FARM_PHASE_REPAIRS) next = next.replace(pattern, good)
  for (const [bad, good] of FINAL_TEXT_REPAIRS) next = next.split(bad).join(good)
  return next
}

function repairElementAttributes(root) {
  const attrs = ['aria-label', 'title', 'placeholder', 'alt']
  const elements = root.querySelectorAll?.('*') || []
  elements.forEach((element) => {
    attrs.forEach((attr) => {
      const value = element.getAttribute(attr)
      const repaired = repairText(value)
      if (repaired !== value) element.setAttribute(attr, repaired)
    })
  })
}

function repairTextNodes(root) {
  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT)
  const nodes = []
  while (walker.nextNode()) nodes.push(walker.currentNode)
  nodes.forEach((node) => {
    const repaired = repairText(node.nodeValue)
    if (repaired !== node.nodeValue) node.nodeValue = repaired
  })
}

export function installTextRepair() {
  if (typeof window === 'undefined' || !document?.body) return
  const run = () => {
    repairTextNodes(document.body)
    repairElementAttributes(document.body)
  }
  run()
  const observer = new MutationObserver(() => run())
  observer.observe(document.body, { childList: true, subtree: true, characterData: true, attributes: true })
}

